sspBC Bid Adapter: remove dependence on auctionId, improve notifications
prebid/Prebid.js pull request #10222
Opened 2023-07-12 12:13 UTC by wojciech-bialy-wpm

## Type of change
- [x] Bugfix
- [x] Feature

## Description of change
Update adapter:
- remove dependence on auctionId property (see https://docs.prebid.org/dev-docs/pb8-notes.html#transaction-identifiers-are-now-reliable-and-opt-in)
- add bidViewable notification (called by Bid Viewability - GAM module)
- add bid type (banner / native)  to notification payload
- replace native_dom_id macro in javascript trackers

This is the last update of 5.x branch of the adapter, before switching to ortbConverter

## Other information

2023-07-12 14:33 UTC, patmmccann approved these changes

2023-07-12 14:34 UTC, patmmccann requested changes
please fix test failures

2023-07-13 08:28 UTC, wojciech-bialy-wpm commented
Tests updated (sorry for that!).

2023-07-18 14:31 UTC, ChrisHuie approved these changes

2023-07-18 14:39 UTC, merged