Lm kiviads
prebid/Prebid.js pull request #10415
Opened 2023-08-30 12:02 UTC by KiviAds

## Type of change
- [x] New bidder adapter

## Description of change
New prebid adapter to connect to kiviads.com demand source

- contact email of the adapter’s maintainer: pavlo@xe.works
- test parameters for validating bids:
```
[
    {
        code: 'test-banner',
        mediaTypes: {
            banner: {
                sizes: [[300, 250]],
            }
        },
        bids: [
            {
                bidder: 'lm_kiviads',
                params: {
                    env: 'lm_kiviads',
                    placement: '40',
                    ext: {}
                }
            }
        ]
    },
    {
        code: 'test-video',
        sizes: [ [ 640, 480 ] ],
        mediaTypes: {
            video: {
                playerSize: [640, 480],
                context: 'instream',
                skipppable: true
            }
        },
        bids: [{
            bidder: 'lm_kiviads',
            params: {
                env: 'lm_kiviads',
                placement: '40',
                ext: {}
            }
        }]
    }
];
```

## Other information
Docs PR: https://github.com/prebid/prebid.github.io/pull/4829

2023-09-01 20:20 UTC, bretg commented
@KiviAds - would it be possible to change your `placement` param to `pid` to make it match your server-side parameter?

2023-09-04 17:46 UTC, KiviAds commented
change placement -> pid according to server-side parameters

2023-09-08 07:57 UTC, KiviAds commented
@lksharma Hi, could you please check this pr? Thank you

2023-09-27 14:41 UTC, lksharma submitted a review, later dismissed
LGTM

2023-09-28 16:06 UTC, lksharma requested changes

2023-10-03 08:32 UTC, KiviAds commented on modules/lm_kiviadsBidAdapter.js
> +  aliases: ['kivi', 'kiviads'],
@lksharma, thanks for the information. The mistake has been fixed

2023-10-03 15:06 UTC, lksharma approved these changes
LGTM

2023-10-03 15:08 UTC, merged