relevantBidAdapter: support s2s
prebid/Prebid.js pull request #10610
Opened 2023-10-13 15:45 UTC by hugolm84

## Type of change

- [x] Feature

## Description of change

The `relevantdigital` bid adapter now supports s2s configurations and need to transform params so that server side parameters are valid.

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page. -->

## Other information

2023-10-17 17:27 UTC, spotxslagle approved these changes
LGTM

2023-10-27 13:29 UTC, patmmccann commented
@bretg could you take a look; does this make your effort on another issue more difficult? 

Also this has no tests

2023-10-30 18:10 UTC, bretg commented
Talked to Patrick. The concern is that `transformBidParams` is something we'd hope to deprecate at some point so the client-side adapter is not necessary for server-side bidders. We'll bring up the topic in the next PMC meeting

2023-11-01 14:14 UTC, bretg requested changes
Add unit tests please

2023-11-03 08:55 UTC, hugolm84 commented
> Add unit tests please

Fixed

2023-11-03 12:06 UTC, bretg approved these changes

2023-11-03 16:57 UTC, merged