FreeWheel SSP Adapter: add gvlid in spec
prebid/Prebid.js pull request #10654
Opened 2023-10-30 13:24 UTC by xwang202

## Type of change

- [X] Maintainence

## Description of change
FreeWheel SSP Adapter: add gvlid in spec

2023-10-30 13:49 UTC, patmmccann requested changes

2023-10-30 13:49 UTC, patmmccann commented on modules/freewheel-sspBidAdapter.js
> +      if (typeof config.getConfig('content') === 'object') {
Please prefer the openrtb specification; this is incorrect

2023-10-31 09:03 UTC, xwang202 commented
Code updated. Please double check.

2023-11-01 15:20 UTC, patmmccann approved these changes

2023-11-01 15:21 UTC, merged