Video module: log error when adUnit provides unknown player div ID
prebid/Prebid.js pull request #10664
Opened 2023-10-30 18:51 UTC by dgirardi

## Type of change

- [x] Bugfix

## Description of change

Partial fix for https://github.com/prebid/Prebid.js/issues/10637

2023-11-03 19:36 UTC, karimMourra requested changes

2023-11-03 19:38 UTC, karimMourra commented
@dgirardi thanks for the fix! I wanted to open a separate PR with a suggestion but I got an error; instead I pushed a commit directly, if you disagree with my proposed changes let me know and i'll roll it back.

2023-11-03 19:56 UTC, karimMourra commented on modules/videoModule/index.js
> +
```suggestion

```

2023-11-03 19:56 UTC, karimMourra commented on modules/videoModule/index.js
> +
```suggestion

```

2024-01-02 22:48 UTC, karimMourra approved these changes

2024-01-30 21:33 UTC, patmmccann approved these changes

2024-01-30 21:33 UTC, merged