ZetaGlobalSsp adapter: support topics module
prebid/Prebid.js pull request #10803
Opened 2023-12-06 14:24 UTC by asurovenko-zeta

## Type of change
- [x] Feature

## Description of change
Support new module **topicsFpdModule**
Providing segment ids to **payload.user.data[].segment[]**

2023-12-06 14:28 UTC, asurovenko-zeta commented on modules/zeta_global_sspBidAdapter.js
> +      return document.browsingTopics();
@ChrisHuie may I ask you to help me with understanding this

2023-12-06 18:33 UTC, patmmccann requested changes
must use our methods

2023-12-06 18:33 UTC, patmmccann commented on modules/zeta_global_sspBidAdapter.js
> +      return document.browsingTopics();
you're not allowed to call this; the topics module exists and does it; you can read its results in ortb2.user.data

2023-12-27 17:28 UTC, patmmccann approved these changes

2023-12-27 17:28 UTC, merged