OpenX Bid Adapter: add ortb2Imp to PAAPI auctionSignals
prebid/Prebid.js pull request #11012
Opened 2024-01-30 22:10 UTC by laurb9

## Type of change
- [x] Feature
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?

## Description of change
Inject the OpenRTB `imp` request object into PAAPI `auctionSignals.ortb2Imp`, to expose contextual slot information such as `banner.formats` to all PAAPI component buyers under the OpenX seller.

## Other information

2024-02-01 13:37 UTC, patmmccann commented
Why not do this in the PAAPI module?

2024-02-01 13:37 UTC, patmmccann requested changes
Let's do this in the module, no?

2024-02-01 17:03 UTC, laurb9 commented
> Why not do this in the PAAPI module?

That would be my preference also (to replace the current `prebid.ortb2Imp` with this). I had a quick chat with @dgirardi last year about this, it seemed less straightforward than I'd hoped. This is an interim solution to avoid having to populate it in the exchange, and we'd drop it if/when the PAAPI module implements it.

Since now Demetrio is working on the PAAPI module refactor, maybe it's time to take another look ?

2024-02-01 17:20 UTC, dgirardi commented
This can't be done in general because, in general, there's no `imp` object.  (We already include `ortb2Imp` as defined by the publisher, but this is looking for the complete request with `banner` and so on, which is up to each adapter).

We'd like to do it in ortbConverter but AFAIK there's still no standard way to return fledge configs in ortb, so we don't have a home for it there either.

2024-02-01 17:26 UTC, dgirardi commented on modules/openxBidAdapter.js
> +              ortb2Imp: context.impContext[bidId]?.ortbRequest?.imp?.[0],
you can use `context.impContext[bidId]?.imp` to get the precise imp tied to the bid id (instead of the first in the request)

2024-02-01 19:43 UTC, patmmccann reviewed
i follow now, ty

2024-02-03 15:54 UTC, ncolletti approved these changes
looks good to me

2024-02-03 15:56 UTC, merged