eight pod init
prebid/Prebid.js pull request #11260
Opened 2024-03-27 00:17 UTC by GreDiSe

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

## Other information

2024-03-28 14:19 UTC, GreDiSe commented
I'm confused a bit, I get CI errors that does not relate to my updates
<img width="1073" alt="Screenshot 2024-03-28 at 16 14 51" src="https://github.com/prebid/Prebid.js/assets/29945710/49673db6-33fb-429b-884d-fcd11a584fd1">

Could you please help me with them?

2024-04-01 16:14 UTC, ChrisHuie commented
@GreDiSe rerunning tests. Hopefully that solves the issue

2024-04-01 16:27 UTC, ChrisHuie commented
@GreDiSe I tried rerunning the tests and still am getting these adapter errors. Can you try pulling in the current version of master and see if that fixes the tests issue?

2024-04-15 09:55 UTC, GreDiSe commented
@spotxslagle  i fixed build, now it works. Could you please review the PR?

2024-04-18 19:53 UTC, spotxslagle requested changes
Just one small change, then I can approve.

2024-04-18 19:53 UTC, spotxslagle commented on test/spec/modules/eightPodAnalyticsAdapter_spec.js
> +describe('', function() {
Please identify this as the adapter, it will make these tests much easier to identify if there are failures.

2024-04-22 12:39 UTC, ChrisHuie commented
@GreDiSe @spotxslagle e2e tests hopefully will work on this go around but no worries if just the e2e tests are failing here.

2024-04-22 17:20 UTC, spotxslagle approved these changes

2024-04-22 20:30 UTC, GreDiSe commented
Thanks a lot for review and your approval

2024-04-23 20:29 UTC, GreDiSe commented
Could you please tell me when are you planning to merge the PR? I saw that doc Pr cant be merged until release.

2024-04-29 08:49 UTC, GreDiSe commented
@ChrisHuie Do mind me asking. I'd like to know when you are planing to do a release and this changes appears there?

2024-05-02 14:38 UTC, merged