Handling User-Sync URL and passing custom object with bid request
prebid/Prebid.js pull request #11326
Opened 2024-04-11 10:16 UTC by kalidas-alkimi

## Type of change

- [ ] Feature

- [No] Does this change affect user-facing APIs or examples documented on http://prebid.org?

## Description of change

## Other information

2024-04-15 14:21 UTC, kalidas-alkimi commented
Hi 

I am not sure why the e2etest is failing,  Could you please check this and help on this failure? if it's possible could you please rerun the e2etest from your side? thanks.

2024-04-15 17:34 UTC, ChrisHuie commented
> Hi
> 
> I am not sure why the e2etest is failing, Could you please check this and help on this failure? if it's possible could you please rerun the e2etest from your side? thanks.

Sometimes the e2e testing is flaky. Don't worry about it.

2024-04-18 08:42 UTC, kalidas-alkimi commented
Hello

We are waiting for his change to be merged, Could you please check and approve it? Thanks.

2024-04-18 18:37 UTC, robertrmartinez requested changes

2024-04-19 14:14 UTC, kalidas-alkimi commented on modules/alkimiBidAdapter.js
> +      if (!iframeList || typeof iframeList !== 'object') return [];
updated

2024-04-23 08:46 UTC, kalidas-alkimi commented on modules/alkimiBidAdapter.js
> +      if (!iframeList || typeof iframeList !== 'object') return [];
@robertrmartinez   Could you please check the latest changes and approve? Thanks.

2024-04-25 08:48 UTC, kalidas-alkimi commented
Hello  @robertrmartinez  / @ChrisHuie 

Could you please check this change and approve it? We are completely blocked deliver this change. Thanks.

2024-04-25 15:54 UTC, robertrmartinez approved these changes

2024-04-25 15:54 UTC, merged