Discovery Bid Adapter : get UTM tag data
prebid/Prebid.js pull request #11380
Opened 2024-04-23 09:39 UTC by ecoeco163

## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

get UTM tag data

## Other information

2024-04-26 16:09 UTC, patmmccann approved these changes

2024-04-26 16:10 UTC, patmmccann requested changes
needs tests

2024-05-06 03:59 UTC, ecoeco163 commented
Hi, I have add unit test

2024-05-06 20:58 UTC, ChrisHuie approved these changes

2024-05-06 20:58 UTC, merged