Discovery Bid Adapter: Fix window.top bug
prebid/Prebid.js pull request #11511
Opened 2024-05-17 15:47 UTC by lhxx121

## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter  
- [ ] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Fix bugs caused by Same-Origin Policy

## Other information

2024-05-30 08:17 UTC, lhxx121 commented
@ChrisHuie Hi, sorry to bother you, could you please help me cr it? This submission is very important to us.❤️

2024-05-30 12:05 UTC, patmmccann requested changes

2024-06-07 16:20 UTC, Rothalack commented
The code changes look good, but I am unable to checkout this pr and test. I think you need to rebase master. It doesn't make sense to me why, these changes shouldn't conflict, but I don't want to try to rebase or change anything on my end to get this working.

2024-06-11 10:31 UTC, lhxx121 commented on modules/discoveryBidAdapter.js
> +    dm = win.top.navigator.deviceMemory;
I understand. I will modify and submit immediately

2024-06-11 10:32 UTC, lhxx121 commented
@Rothalack I understand. I will modify and submit immediately

2024-06-11 18:19 UTC, Rothalack approved these changes
I still had to manually check this out into a new branch for myself to test. Everything is working in testing. I still don't know why github complains about this when I try to gh pr checkout. I think it's because there's some divergence somewhere in your commit history that makes the simple gh checkout not work. I don't see any reason why that divergence is going to cause any issues. There's no conflicts. So I think we can just ignore it and merging this will work fine.

2024-06-13 20:42 UTC, patmmccann approved these changes

2024-06-13 20:42 UTC, merged