Taboola Bid Adapter: fix ortb2 user override issue
prebid/Prebid.js pull request #11516
Opened 2024-05-19 09:53 UTC by ahmadlob

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter  
- [ ] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

user object entities in first party data (ortb2) not passed within the server generated request.
In this PR, fixed the override issue and passing what the ortb convertor generated "user" field as it is

## Other information

2024-05-19 10:53 UTC, dmitry-taboola approved these changes

2024-05-19 10:54 UTC, dmitry-taboola approved these changes

2024-05-21 17:44 UTC, spotxslagle requested changes
I'd just like one small test added. Other than that, it LGTM

2024-05-21 17:44 UTC, spotxslagle commented on test/spec/modules/taboolaBidAdapter_spec.js
> +        expect(res.data.user.id).to.deep.equal(bidderRequest.ortb2.user.id)
I would also like to see a test that regs.coppa is being set.

2024-05-21 21:37 UTC, ahmadlob commented
@spotxslagle  added more tests, thanks!

2024-05-22 18:42 UTC, spotxslagle approved these changes

2024-05-26 21:08 UTC, ahmadlob commented
@ChrisHuie When approximately this PR will be merged? thanks

2024-05-29 20:26 UTC, merged