IMDS Bid Adapter: support video.plcmt
prebid/Prebid.js pull request #11615
Opened 2024-05-29 23:50 UTC by tgcallaway

## Type of change
- [x] Updated bidder adapter 

## Description of change
Add support for video.plcmt

2024-05-30 01:26 UTC, ChrisHuie commented
@tgcallaway can you fix the newline issue at the end of your adapter file so it passes lint checks please?

2024-05-30 10:52 UTC, patmmccann approved these changes

2024-05-30 10:54 UTC, patmmccann requested changes
Fix your linting error please

2024-05-30 19:02 UTC, tgcallaway commented
@patmmccann @ChrisHuie thank you, linting error resolved.

2024-06-03 14:23 UTC, ChrisHuie approved these changes

2024-06-03 14:27 UTC, merged