Preciso Bid Adapter : update on valid request checks
prebid/Prebid.js pull request #11745
Opened 2024-06-10 06:52 UTC by NikhilGopalChennissery

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter  
- [ ] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

## Other information

2024-06-10 11:52 UTC, patmmccann commented
It appears your duplication fixes were tricks to avoid the report. Please actually fix

2024-06-10 12:49 UTC, patmmccann requested changes

2024-06-10 12:49 UTC, patmmccann commented on modules/precisoBidAdapter.js
>        }
There are many tricks to fool the duplication detector in this pr. Remove them.

2024-06-11 09:45 UTC, NikhilGopalChennissery commented
Hi @patmmccann 
Sorry for the changes we have made. We are beginners on the Prebid platform. We have tested the current code changes locally and confirmed that it is working fine.

We created our Adapter by referring to the documentation on prebid.org and examining other bidAdapters' code as well. We have  noticed that some of  codes is common in some other adapters as well. 

I am ready to modify the code as you suggested. I would like to clarify a few points:

We are accessing storage manager from the BidAdapter itself. Is that okay?
For building Bid requests and Bid responses, should I create a common library function and use that library in our bid adapter.?

Please correct me if I am wrong.

 Thank you.

2024-06-16 12:46 UTC, patmmccann commented
You may access storage manager, however you will not have access by default, publishers must grant access. 

Yes, importing functions from common libraries should reduce code duplication. Your particular adapter looks similar to at least one adapter maintained by teqblaze, who I believe has that effort underway. You may wish to coordinate with them or look at their patterns

https://github.com/MaksymTeqBlaze/Prebid.js/commit/0249eb7a258d610e937a114676e24c1d3f6c956e

2024-06-19 04:36 UTC, NikhilGopalChennissery commented
Hi @patmmccann ,

Thanks for your update. I hope this will help us  to remove the code duplications

We will work on this and update the PR ASAP.

Thank you!

2024-06-20 06:42 UTC, closed without merging

2024-06-26 11:59 UTC, NikhilGopalChennissery commented
Hi @patmmccann ,

I have created a new PR ( https://github.com/prebid/Prebid.js/pull/11868 )  with our latest changes to remove the code duplication.