UserID Submodule change to conform with publisher's configuration
prebid/Prebid.js pull request #12032
Opened 2024-07-24 14:54 UTC by p-ribeiro

## Type of change
- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter  
- [ ] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

## Description of change
Fixing the problems described at https://github.com/prebid/Prebid.js/issues/10710.
We are now saving the ID in cookie or html5, respecting the storage.type parameter. 
We also changed our logic to get the ID from our API.

2024-07-24 18:03 UTC, p-ribeiro commented
Can someone give me an explanation on why did my test failed? It seems that what failed are another modules tests. 

For example the IntentQ and imuId module...

```

166) should return expired is true
     imuId module getLocalData()
     AssertionError: expected { Object (id, ppid, ...) } to deeply equal { Object (id, ppid, ...) }
    at Context.<anonymous> (/tmp/_karma_webpack_724924/commons.js:314947:49)

167) should save data in cookie if storage type is "cookie"
     IntentIQ tests
     AssertionError: expected null to not equal null
    at Context.<anonymous> (/tmp/_karma_webpack_724924/commons.js:317159:43)

168) "before each" hook for "should set cmpData.us_privacy if uspData exists"
     IntentIQ tests IntentIQ consent management within getId
```

2024-07-31 14:37 UTC, patmmccann commented on modules/naveggIdSystem.js
> +import * as ajaxLib from '../src/ajax.js';
please only import what you need

2024-07-31 14:38 UTC, patmmccann requested changes
Thanks so much, one tweak requested

2024-08-02 16:59 UTC, p-ribeiro commented
> Thanks so much, one tweak requested
The change was done as requested with my latest commit

2024-08-02 18:58 UTC, p-ribeiro commented
May I ask a question here?

Is it permitted to add a cookie saver, as a default option, if the client does not implemente the storage options?

2024-08-05 13:22 UTC, patmmccann commented
The parent module handles the storage writes

2024-08-05 13:23 UTC, patmmccann approved these changes

2024-08-05 13:24 UTC, merged