ImRtdProvider: add bidder function for craft
prebid/Prebid.js pull request #12475
Opened 2024-11-20 10:55 UTC by eknis

## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter  
- [ ] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

## Other information

2024-11-21 16:42 UTC, patmmccann requested changes

2024-11-25 04:25 UTC, eknis commented on modules/imRtdProvider.js
> +    craft: function (bid, data, moduleConfig) {
@patmmccann 
I removed the settings for 'craft' that I had added and changed it to only add the imuid parameter.
The previous support will not be removed this time for backward compatibility.

2024-12-06 05:03 UTC, eknis commented
@patmmccann
 I add to set the value in ortb2 for the adapters to process. Thank you for your review.

2024-12-26 16:46 UTC, patmmccann approved these changes

2024-12-26 16:46 UTC, merged