Missena Bid Adapter : send bid sizes
prebid/Prebid.js pull request #12560
Opened 2024-12-09 15:41 UTC by pdamoc

## Type of change

- [x] Feature
 
## Description of change

We need to send the bid sizes in order to optimize the response for new use cases.

2024-12-26 18:45 UTC, patmmccann requested changes
Please make out use a common utility

2024-12-26 18:45 UTC, patmmccann commented on modules/missenaBidAdapter.js
> +function normalizeSizes(bidSizes) {
Please make this a utility function in /libraries somewhere

2025-01-13 14:52 UTC, pdamoc commented on modules/missenaBidAdapter.js
> +function normalizeSizes(bidSizes) {
Sorry for such a late reply. I was on vacation. I hope that this refactor is OK

2025-01-14 09:06 UTC, pdamoc commented
Sorry for the noise in the commits, I initially put the function the the utils module but then I looked more carefully this morning and understood where it was requested to be put.

2025-01-15 13:13 UTC, patmmccann approved these changes

2025-01-15 13:13 UTC, merged