Adtrgtme bid adapter changes
prebid/Prebid.js pull request #12580
Opened 2024-12-16 10:40 UTC by tarasmatokhniuk

## Type of change

- [x] Bugfix
- [x] Refactoring bidder adapter  
- [x] Refactoring bidder adapter tests 

## Description of change
- Adapter and server mismatch. Use string to set up site.id
- Add optional adapter fields. Added strict placement identification as tagid and currency

2025-01-01 16:50 UTC, patmmccann commented on modules/adtrgtmeBidAdapter.js
> +      page: deepAccess(bR, 'refererInfo.page'),
Please use optional chaining

2025-01-01 16:51 UTC, patmmccann commented on modules/adtrgtmeBidAdapter.js
> +  const ip = deepAccess(bid, 'params.bidOverride.device.ip') || deepAccess(bid, 'params.ext.ip');
Please support ortb2.device.ip

2025-01-01 16:52 UTC, patmmccann commented on modules/adtrgtmeBidAdapter.js
> +      ua: navigator.userAgent,
Please get from the request object

2025-01-01 16:53 UTC, patmmccann commented on modules/adtrgtmeBidAdapter.js
> +function appendSiteData(oR, bid) {
Why are you picking and choosing parts of the site object instead of taking the whole thing?

2025-01-01 16:54 UTC, patmmccann commented on modules/adtrgtmeBidAdapter.js
> +  const site = deepAccess(bid.ortb2, 'site') || undefined;
Please eliminate all use of deepAccess

2025-01-01 16:54 UTC, patmmccann commented on modules/adtrgtmeBidAdapter.js
> +            advertiserDomains: b.adomain || [],
Networkid can be very helpful if you have it

2025-01-01 16:56 UTC, patmmccann commented on modules/adtrgtmeBidAdapter.js
> +        const p = response.body?.ext?.pixels;
Getting the user syncs off the response is a bit risky, consent may have changed

2025-01-01 16:56 UTC, patmmccann approved these changes
Mostly good, a few tweaks requested

2025-01-01 16:56 UTC, patmmccann requested changes
A few tweaks

2025-01-03 13:07 UTC, tarasmatokhniuk commented on modules/adtrgtmeBidAdapter.js
> +            advertiserDomains: b.adomain || [],
Thx, but we use site.id instead

2025-01-03 16:07 UTC, tarasmatokhniuk commented
Hello @patmmccann 
Please take a look at the commit. Thank you for your time

2025-01-03 16:27 UTC, tarasmatokhniuk commented on modules/adtrgtmeBidAdapter.js
> +  const site = deepAccess(bid.ortb2, 'site') || undefined;
done

2025-01-03 16:27 UTC, tarasmatokhniuk commented on modules/adtrgtmeBidAdapter.js
> +function appendSiteData(oR, bid) {
Remaked it

2025-01-03 16:30 UTC, tarasmatokhniuk commented
Is everythiI think I've fixed everything, and all checks have passed. Is it good now?

2025-01-04 09:26 UTC, patmmccann approved these changes

2025-01-04 09:26 UTC, merged