merkleId Identity submodule submission
prebid/Prebid.js pull request #5577
Opened 2020-08-06 18:26 UTC by angelamerkelprebid

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [X] Other

## Description of change
This adds the Merkle id system to prebid github project as a submodule to the userId module. It requires two Merkle supplied identifiers, partner key (ptk) and publisher id (pubid). These must be supplied by merkleinc.com before the endpoint will work. Please get in touch at https://merkury.merkleinc.com/contact

2020-08-06 20:00 UTC, harpere commented
@angelamerkelprebid - Tests failed.

2020-08-06 20:47 UTC, angelamerkelprebid commented
docs PR is https://github.com/prebid/prebid.github.io/pull/2193

2020-08-24 11:02 UTC, smenzer requested changes
missing eids.js entry and a mismatch in defining the id object

2020-08-24 19:41 UTC, angelamerkelprebid commented on test/spec/modules/eids_spec.js
> +        eid: 'some-random-id-value'
Thank you very much @smenzer !!

2020-08-24 19:42 UTC, angelamerkelprebid commented on test/spec/modules/eids_spec.js
> +        eid: 'some-random-id-value'
Tests appear to have passed this time.

2020-08-25 07:56 UTC, smenzer approved these changes

2020-08-25 14:41 UTC, angelamerkelprebid commented
Thanks for the review @smenzer ! @jlukas79 looking forward to your comments.

2020-08-27 15:45 UTC, angelamerkelprebid commented
Thanks so much @jlukas79 and @smenzer ! Could one of you kindly merge?

2020-08-28 09:58 UTC, merged