add quantcast ID submodule
prebid/Prebid.js pull request #5727
Opened 2020-09-10 16:18 UTC by mckurt

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

## Description of change
This adds quantcast user ID submodule. The submodule reads Quantcast first party cookie and passes the value to prebid bidding adapters. Currently, the submodule doesn't need any configuration parameters. The code is tested using with unit tests and userId_example.html. The code coverage on the submodule is 85.71%. Please contact asig@quantcast.com for any issues.

2020-09-10 16:57 UTC, mckurt commented on integrationExamples/gpt/userId_example.html
> +                        sizes: [[300,250],[300,600],[728,90]]
I noticed that a recent PR tackled the same issue (https://github.com/prebid/Prebid.js/pull/5606), but I was still getting errors if the sizes aren't defined inside the _banner_ object. I can move this to a different PR if that'd be better.

2020-09-11 09:22 UTC, smenzer requested changes
generally looks good to me, just a minor change in the test around cookies.

2020-09-11 09:22 UTC, smenzer commented on test/spec/modules/quantcastIdSystem_spec.js
> +    window.document.cookie = '__qca= ; expires = Thu, 01 Jan 1970 00:00:00 GMT;';
can you use the `storage.setCookie()` function for this instead?

2020-09-11 22:00 UTC, jlukas79 reviewed
Looks good to me, will approve once changes above completed and conflicts resolved

2020-09-15 21:14 UTC, mckurt commented
@jlukas79 @smenzer Thanks for the review. I addressed the comment. Will attach a link to the documentation PR soon.

2020-09-15 23:10 UTC, mckurt commented
Here is the documentation PR: https://github.com/prebid/prebid.github.io/pull/2339 

I also updated the description.

2020-09-15 23:13 UTC, jlukas79 approved these changes

2020-09-16 12:15 UTC, smenzer approved these changes
LGTM

2020-09-16 12:15 UTC, merged