Add adrelevantis adapter
prebid/Prebid.js pull request #5735
Opened 2020-09-11 17:47 UTC by ghguo

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2020-09-21 14:39 UTC, bretg commented
Docs PR https://github.com/prebid/prebid.github.io/pull/2329

2020-09-23 19:27 UTC, jsnellbaker requested changes
Hi @ghguo 

I checked through the code and it largely seems good.  There are a few items that should be reviewed and addressed.

I tested the 3 different media types using the parameters in the md file and they rendered successfully.

I checked the test-coverage and it was just a bit below the accepted threshold.  It was at 74.41% and we'd like to see at least 80%.  Could you take a look at the unit tests and either add tests or modify the existing ones to improve the coverage?

I think we should good once the above is addressed.

Thanks.

2020-09-24 19:11 UTC, ghguo commented on modules/adrelevantisBidAdapter.js
> +  } else {
Hi jsnellbaker,

The suggested changes have been made. Please advise.

Thanks,
Gary

2020-09-25 18:40 UTC, jsnellbaker approved these changes
Thanks for making the updates; LGTM

2020-09-25 18:40 UTC, merged