Integrate option to pass clickThrough urls to renderAd method
prebid/Prebid.js pull request #5796
Opened 2020-09-29 11:04 UTC by renebaudisch

## Type of change
- [x] Feature

## Description of change
This change enables publishers/marketers to count clicks on prebid inventory in their distributing adserver.
The publisher may call render ad with a third param accepting an object where right now only clickThrough will be checked but can be extended.
If this property is set we will replace any occurrence of ${CLICKTHROUGH} inside the properties ad and adUrl with the transmitted option.
If no occurrence is found nothing will be replaced.

## Other information
To make use of this feature bidAdpaters just have to respond with tags including this macro to pass it to their param and system

2020-09-30 16:52 UTC, patmmccann commented
Chatting in the js committee today, we're hoping #5760 gets merged first, as renderers on display to track clicks might intefere with multiformat ads that need renderer on outstream.

2020-09-30 16:54 UTC, patmmccann commented
Also, needs tests, thanks for the contribution!

2020-09-30 22:36 UTC, harpere requested changes
needs some validation and unit tests

2020-09-30 22:36 UTC, harpere commented on src/prebid.js
> +        const { clickThrough } = options;
should validate that `options` is defined.

2020-09-30 22:36 UTC, harpere commented on src/utils.js
> +  return str.replace(/\$\{CLICKTHROUGH\}/g, clicktag);
should validate that `clicktag` is defined and not NULL, maybe that it's a string.

2020-10-01 16:07 UTC, harpere requested changes
updates look good, thx, but still needs unit tests

2020-10-01 16:46 UTC, renebaudisch commented
> updates look good, thx, but still needs unit tests

Ahm, yeah, tried my best... Is my first one ever, hope it fits.

2020-10-02 14:49 UTC, renebaudisch commented
Closed #5816 in favor to #5820

2020-10-05 04:07 UTC, harpere approved these changes

2020-10-07 16:01 UTC, jsnellbaker approved these changes

2020-10-07 16:01 UTC, merged

2021-02-02 20:21 UTC, bretg commented
I missed this one -- still kinda unclear on the real-world use case. The Prebid Universal Creative doesn't support this. 

@renebaudisch - could you outline a sample usage scenario so we can document this somewhere?

2021-02-03 08:43 UTC, renebaudisch commented
When using an adserver to render or deliver the prebid response there is actually no option to count clicks by the delivering adserver by passing their clickThrough as one normally would do when adding a redirect for an IO booking.

By adding this options we could provide an clickthrough url from the adserver to the renderAd method so the adserver of the publisher would also count clicks on prebid creatives as we cannot right now.

This should also affect some reports and statistics of some adservers as the average clickrate right now has either to avoid calculate them or using their AIs by a clickrate of 0,00% what actually reduces this rate.

Sure, both sides have to support this, so the adCode response has to use a macro and the publisher has to provide the clickthrough but right now I just couldn't and this just gives us this possibility.
But if one of them won't nothing will change either for noone...