Create reforgeBidAdapter.js
prebid/Prebid.js pull request #5842
Opened 2020-10-09 11:46 UTC by Shivani77777

## Type of change

- [ ] Bugfix
- [ ] Feature
- [x ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: 'reforge',
                       params: {
                           placementId: 'mediumrectangle-demo',
                           categories: ['Games'] // optional: categories of page
                       }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ shivani.garg@svgmedia.in] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2020-10-13 20:51 UTC, robertrmartinez commented
@Shivani77777 A corresponding test file and .md file is required.

Please add unit tests and a markdown which contain valid test params which return test ads.

2020-10-14 07:40 UTC, FilipStamenkovic requested changes
@Shivani77777 @robertrmartinez  
This new bidder is exactly the same as `ablida` bidder we already have in pbjs. Only `code` and `endpoint` are different.    
I think this bidder should be defined as alias?

2020-10-14 07:40 UTC, FilipStamenkovic commented on modules/reforgeBidAdapter.js
> +const ENDPOINT_URL = 'http://use.reforge.in/bid?rtb_seat_id=0011&secret_key=wzP8eKAVkc&type=prebid&appid=40';
You should use `https` endpoint.

2020-10-14 07:40 UTC, FilipStamenkovic commented on modules/reforgeBidAdapter.js
> +      bid.ttl = config.getConfig('_bidderTimeout');
Are you sure this is what you want, `bidderTimeout` is in milliseconds, while `ttl` is in seconds?

2020-10-20 12:34 UTC, closed without merging