[AD-963] - Update JW Player RTD Provider for compliance with RTD Module Phase 3
prebid/Prebid.js pull request #5844
Opened 2020-10-10 04:00 UTC by karimMourra

## Type of change
- [x] Refactoring (no functional changes, no api changes)

## Description of change
This PR is a side-effect of the changes proposed in #5783 and should be merged with it. 
It modifies the JW Player RTD Provider to conform to the desired interface and behavior dictated by the RTD Module 

Additionally, it updates the `gridBidAdapter.js`'s implementation to use the updated  `jwTargeting` property in bid instances instead of the obsolete `realTimeData`. A member from The Media Grid will review these changes.

- contact email of the adapter’s maintainer
karim@jwplayer.com

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information
Prerequisite PR: #5783

2020-10-13 08:05 UTC, TheMediaGrid approved these changes

2020-10-15 17:16 UTC, Fawke requested changes
Hi @karimMourra,

Thanks for the PR. Overall, this looks good. While I was testing it, using the page your provided, the networks calls to your endpoint returns `400`.

Second concern that I had was regarding the number of times you are sending a request to your endpoint. Is there anyway, we can send all mediaIds as a payload to only one request to your backend?

Also, we'd require a docs PR for prebid.org documenting all your params. Please refer to browsi's [doc](https://github.com/prebid/prebid.github.io/pull/2268/files?file-filters%5B%5D=.jpg&file-filters%5B%5D=.md#diff-f7318610c4be676b682b1bcfe5d12fa2e0552e339a609e5050d4a58e26e9769b) for more details on the format.

2020-10-15 20:34 UTC, karimMourra commented
Hi @Fawke thank you for the review! The page provided uses placeholder values, so it is normal for the requests to 404. In order for them to succeed, the publisher would have to use his media Ids.

Regarding the multiple requests, that's a great observation. we currently don't have an endpoint for that, but we will make the adjustments when it becomes available. 

Regarding the docs, I will create one! Thank you for raising that

2020-10-16 20:04 UTC, karimMourra commented
@Fawke PR opened for Documentation: https://github.com/prebid/prebid.github.io/pull/2427

2020-10-16 22:21 UTC, karimMourra commented
@Fawke  I added a sample media id for the PR: `'2XZFlRuo'`

2020-10-19 10:43 UTC, Fawke reviewed
@karimMourra

Thanks for providing a sample media Id which allowed me to do some testing. Just one suggestion, since you're providing an example html page, I would recommend adding a comment saying something like: these are placeholder media Ids, please replace them with your existing Id(s). I know you've written this message in your MD file, but, it's a good idea to include it in the html page as well.

Please try to minimize calls to your backend server in a future PR. 

I'll just wait for you to see this message and add that comment, if not, I'll merge it tomorrow and make sure it makes it to this week's release.

2020-10-19 15:57 UTC, Fawke approved these changes
LGTM

2020-10-20 16:21 UTC, bretg commented
Unit test pass locally. Merging. We'll have to address unrelated failing tests outside of this PR.

2020-10-20 16:21 UTC, merged