userId module: fix auctionDelay submodules with callbacks
prebid/Prebid.js pull request #5891
Opened 2020-10-23 10:34 UTC by FilipStamenkovic

## Type of change
- [x] Bugfix

If the userId submodule provides callback, but it never executes that callback, pbjs will get stuck and it won't request bids.  

This was detected with `identityLink` userId submodule in issue #5882.  

piece of code:

```
if (!storage.getCookie('_lr_retry_request')) {
  setRetryCookie();
  utils.logInfo('A 3P retrieval is attempted!');
  ajax(url, callbacks, undefined, { method: 'GET', withCredentials: true });
}
```

So, for this userId submodule, if there exists `_lr_retry_request` cookie, it will block prebid from requesting bids, because `callbacks` are never called.  

At first, this seems like a bug in submodule, but further digging down in userId module, I found that that there is `setTimeout` for `auctionDelay`, which gets cleared few lines of code afterwards.  

## Description of change

Proposed solution is to call `clearTimeout` only after all submodules have executed their callbacks.

2020-10-30 15:14 UTC, Fawke requested changes
@FilipStamenkovic, Thanks for fixing this, this change looks good. Would it be possible for you to write a unit test for this change? That'll be ideal.

Also, if you can once sync with master and do an `npm install`, circle-ci tests will start passing.

2020-11-02 13:13 UTC, FilipStamenkovic commented
@Fawke Done. I didn't add any new unit tests, I 'fixed' the old ones.  

Old ones were checking that `setTimeout` function is called, but they were not checking that `clearTimeout` was not called.  
I added checks in tests so that we are sure that `clearTimeout` was not called.  

If you run those tests on `master` branch they will fail, but if you run them on this branch they will pass.  

Please let me know if I need to add anything else.

2020-11-03 09:40 UTC, Fawke approved these changes
LGTM

2020-11-03 09:42 UTC, Fawke commented
Adding @robertrmartinez for second review. Feel free to re-assign if busy.

2020-11-09 18:48 UTC, robertrmartinez approved these changes

2020-11-10 08:05 UTC, FilipStamenkovic commented
@Fawke @robertrmartinez Can one of you guys please merge this one?

2020-11-10 10:41 UTC, merged