support IE in aol spec
prebid/Prebid.js pull request #5894
Opened 2020-10-23 23:33 UTC by robertrmartinez

## Type of change
- [X] Bugfix

## Description of change
IE 11 does not support `Object.entries`

Change to simple `forEach`

2020-10-24 09:04 UTC, slimkrazy commented
Thanks for this @robertrmartinez  - I did fix this as soon as I saw the CI build failed in commit 2befbd8ff7816da125ef641e05d8a268aa9b2874 on the same branch, I'm just surprised that it was ever merged.

@mike-chowla  - This is related to https://github.com/prebid/Prebid.js/pull/5886 that was merged yesterday. Please review this and merge in these changes to prevent all builds from continuing to break.

2020-10-27 10:27 UTC, FilipStamenkovic requested changes
I think the goal should be to support aol bidder on IE, not specs.  

Do tests need to be ES5?  

Anyway, circleci is failing because aol bidder is using function not supported on IE, `includes`:  

https://github.com/prebid/Prebid.js/blob/master/modules/aolBidAdapter.js#L119

2020-10-27 16:30 UTC, robertrmartinez commented
@FilipStamenkovic 

Both have to be ES5 compliant actually.

I did not notice the array includes because the Object.entries in the spec was causing IE to fail.

After I pushed this PR then the next failure began to happen.

So we need to fix both.

2020-10-27 18:00 UTC, robertrmartinez commented
okay @FilipStamenkovic 

Passing now.

2020-10-28 09:11 UTC, smenzer commented
@robertrmartinez or @FilipStamenkovic can this get merged now?

2020-10-28 09:15 UTC, FilipStamenkovic approved these changes
LGTM

2020-10-28 09:15 UTC, merged