init bizzclick prebid.js adapter
prebid/Prebid.js pull request #5914
Opened 2020-10-30 07:04 UTC by BizzClick

## Type of change

- [ x] New bidder adapter   

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    placementId: 'hash',
    accountId: 'bizzclickTest'
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
support@bizzclick.com
- [ x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2020-11-06 14:03 UTC, BizzClick commented
Hey @musikele  ! Do you have chance to review my Adpater ?

2020-11-06 17:57 UTC, musikele requested changes
Hi there. Sorry for being late. It seems to me that the code coverage is under 80%, that is the code coverage we require for adapters. 

To test this, 

```
$ npx gulp test-coverage 

$ npx gulp view-coverage
```

2020-11-06 18:06 UTC, musikele reviewed
I added some notes, feel free to go into them.

2020-11-06 18:06 UTC, musikele commented on modules/bizzclickBidAdapter.js
> +      serverResponse = serverResponse.body;
Consider: 

```
if (!serverResponse || !serverResponse.body) return []
serverResponse = serverResponse.body
```

Anyway, it's generally considered a bad practice to modify the input parameter of a function. You may think of assigning it to a newly created variable.

2020-11-16 12:21 UTC, BizzClick commented
Hello @musikele ! Thanks for you review! I have updated my adapter could you please check it?

2020-11-16 17:25 UTC, musikele approved these changes
LGTM

2020-11-16 17:29 UTC, musikele commented
Before final merge, we need to rebase against current master, because there was an issue with a test that prevented the Continuous Integration to work effectively. 
Run these commands: 

```
git pull --rebase origin master 
git push --force 
```

This should fix the Continuous Integration.

2020-11-17 12:57 UTC, BizzClick commented
@musikele I have made rebase to master but I still have problems with CI

2020-11-17 16:34 UTC, musikele commented
@BizzClick this time the problem is less serious. File BizzClickBidAdapter_spec.js is not properly formatted. You may either fix all linting errors manually or run `npx gulp lint` and commit the modified files. Let me know when you're done.

2020-11-19 07:40 UTC, BizzClick commented
Hello, @musikele  ! I would not like to bother you, but I still have CI build error after fix linting. Could you please help me resolve it?

2020-11-19 08:36 UTC, musikele commented
@BizzClick the circleci only needed another spin. Going to merge now.

2020-11-19 08:37 UTC, merged

2020-11-19 16:40 UTC, bretg commented
docs PR https://github.com/prebid/prebid.github.io/pull/2511