Added user sync support into adapter
prebid/Prebid.js pull request #5934
Opened 2020-11-05 09:25 UTC by lemmadev

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

## Description of change

We have added user sync support into our adapter. 

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2020-11-09 20:07 UTC, robertrmartinez requested changes
please add associated unit tests

2020-11-09 20:07 UTC, robertrmartinez commented on modules/lemmaBidAdapter.js
> +import * as utils from '../src/utils';
should include .js extension.

2020-11-10 04:59 UTC, lemmadev commented on modules/lemmaBidAdapter.js
> +import * as utils from '../src/utils';
updated file extension.

2020-11-10 11:00 UTC, FilipStamenkovic requested changes
There are couple of small errors that should be fixed before merging.  

You can just run `gulp lint` and take a look at the output, it will fix `'` vs `"` format and it will let you know about other errors.

2020-11-11 06:42 UTC, lemmadev commented on modules/lemmaBidAdapter.js
> +var USER_SYNC = "https://sync.lemmatechnologies.com/js/usersync.html?"
Fixed format error.

2020-11-11 06:42 UTC, lemmadev commented on modules/lemmaBidAdapter.js
> +    let syncurl = USER_SYNC + "pid=" + pubId;
Fixed format error.

2020-11-11 06:43 UTC, lemmadev commented on test/spec/modules/lemmaBidAdapter_spec.js
> +        expect(spec.getUserSyncs({ iframeEnabled: truev}, {}, { gdprApplies: false, consentString: 'foo' }, undefined)).to.deep.equal([{
Fixed format error and typo error

2020-11-12 16:35 UTC, FilipStamenkovic approved these changes
LGTM

2020-11-12 16:36 UTC, merged