Add PubWise Bid Adapter
prebid/Prebid.js pull request #6044
Opened 2020-11-28 21:17 UTC by GLStephen

## Type of change
- [ x ] New bidder adapter  

Docs PR: https://github.com/prebid/prebid.github.io/pull/2502

## Description of change

Adds the PubWise bidder code.

- test parameters for validating bids

### Banner
```
var adUnits = [
    {
        code: "banner-div",
        mediaTypes: {
        banner: {
            sizes: [[300, 250]]
        }
        },
        bids: [{
            bidder: 'pubwise',
            params: {
                siteId: "xxxxxx",
                spotId: "12345678",
                isTest: true
            }
        }]
    }
]
```
### Native
```
var adUnits = [
    {
        code: 'native-div',
        sizes: [[1, 1]],
        mediaTypes: {
        native: {
            title: {
            required: true
            },
            body: {
            required: true
            },
            image: {
            required: true
            },
            sponsoredBy: {
            required: true
            },
            icon: {
            required: false
            }
        }
        },
        bids: [{
            bidder: 'pubwise',
            params: {
                siteId: "xxxxxx",
                spotId: "N12345678",
                isTest: true
            }
        }]
    }
]
```

- Contact info: stephenj@PubWise.io
- [ X ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- Docs PR: https://github.com/prebid/prebid.github.io/pull/2502

2020-12-02 12:23 UTC, Fawke commented on modules/pubwiseBidAdapter.js
> +const PREBID_NATIVE_HELP_LINK = 'http://prebid.org/dev-docs/show-native-ads.html';
You can probably make this `https` since Prebid.org now has a secure url.

2020-12-02 12:24 UTC, Fawke commented on modules/pubwiseBidAdapter.js
> +  }
What's the purpose of this function? In its current form it is not doing much.

2020-12-02 12:28 UTC, Fawke requested changes
Hi @GLStephen,

Overall the code looks good. I added just a couple of inline review comments that you may wanna look into.

I had a problem getting a bid back while testing using your test params. I was getting a CORS error. I'll attach it for your reference.

<img width="1680" alt="Screenshot 2020-12-02 at 5 58 31 PM" src="https://user-images.githubusercontent.com/14229985/100872582-05c78f00-34c8-11eb-809e-394cdfa03abc.png">

2020-12-03 14:01 UTC, GLStephen commented
@Fawke those updates have been made and we've added our GVLID. The CORS errors on the bidder endpoint is a library waiting to be updated with the functionality to allow a CORS domain "function" on the server side. Which is expected in the next week. Trying not to make everything dependent on everything else to get this out. I'm comfortable with it.

2020-12-04 13:05 UTC, Fawke commented
@GLStephen I'm fine to accept this and trust you to add the CORS library next week.

Just one suggestion, you can add `gvl_id: 842` in the docs PR, in the metadata section.

2020-12-04 14:12 UTC, GLStephen commented
@Fawke I appreciate that, gvlid added: https://github.com/prebid/prebid.github.io/pull/2502/files#diff-c3f2febc9bca4a4526ef5c50b0353dc10703338f9b691a5bc52ef4f7d7139591

2020-12-04 15:10 UTC, GLStephen commented
@Fawke CORS header update made it in this morning

2020-12-07 11:33 UTC, Fawke commented
@GLStephen,

Looks like you made change to the `bidderCode` `pubwise -> pwbid`. Would you mind updating the md files and docs at prebid.org. Rest looks good.

2020-12-09 00:47 UTC, GLStephen commented
@Fawke docs updated

2020-12-09 14:42 UTC, Fawke approved these changes

2020-12-09 14:45 UTC, merged