Price Floors / RP Analytics Update - modelTimestamp
prebid/Prebid.js pull request #6061
Opened 2020-12-01 13:04 UTC by mmoschovas

Price Floors update to include modelTimestamp displaying when the floors file was produced

Rubicon Anaytics Update to pass modelTimestamp if exists

## Type of change

- [ ] Bugfix
- [X ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

1) Price Floors update to include modelTimestamp displaying when the floors file was produced
2) Rubicon Anaytics Update to pass modelTimestamp if exists

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2020-12-02 14:26 UTC, jsnellbaker requested changes
Hi @mmoschovas 

Does this change need a corresponding Docs update?

I'm assuming this `modelTimestamp` param is coming from the publisher's priceFloor config object, but I don't see anything referencing the value in the current docs.  

If the value is coming from somewhere else, can you please clarify where it's set?

2020-12-02 16:12 UTC, mmoschovas commented
Issue described here: https://github.com/prebid/Prebid.js/issues/6034

@bszekely1 is there an update for the docs as described above?

2020-12-07 23:53 UTC, bszekely1 commented
> Issue described here: #6034
> 
> @bszekely1 is there an update for the docs as described above?

I pushed the docs changes to production already prematurely. No worries. When it's released docs are already up.

2020-12-08 00:05 UTC, robertrmartinez approved these changes

2020-12-09 18:54 UTC, jsnellbaker approved these changes

2020-12-09 18:54 UTC, merged