Optout: UserId module and Sharedid submodule
prebid/Prebid.js pull request #6068
Opened 2020-12-02 00:11 UTC by SKOCHERI

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2020-12-02 00:13 UTC, SKOCHERI commented
The shared Id changes are in pull request https://github.com/prebid/shared-id/pull/10

2020-12-02 08:12 UTC, smenzer requested changes
Can you please explain the workflow here? You didn't provide a PR description and I want to make sure your intentions align to how the code is written and what I understand from it.

I also don't see any tests related to the actual optout method in user id module, so can you please add coverage?

Thanks!

2020-12-02 08:12 UTC, smenzer commented on modules/sharedIdSystem.js
> +const SYNC_SVC = SHAREDID_URL + '/iframe/optout';
I get a 404 when calling https://id.sharedid.org/iframe/optout ... is this ready to go?

2020-12-02 08:13 UTC, smenzer commented on modules/sharedIdSystem.js
> +const SYNC_SVC = SHAREDID_URL + '/iframe/optout';
never mind...I missed this comment, sorry! https://github.com/prebid/Prebid.js/pull/6068#issuecomment-736902048

2021-04-14 10:55 UTC, ChrisHuie commented
@SKOCHERI is this pr still relevant or active or can I close it out?

2021-04-16 17:10 UTC, SKOCHERI commented
> @SKOCHERI is this pr still relevant or active or can I close it out?

Closing this pull request

2021-04-16 17:10 UTC, closed without merging