New feature: PBS anti alias
prebid/Prebid.js pull request #6150
Opened 2020-12-24 13:01 UTC by GeneGenie

## Type of change
- [x] Feature
- [x] Does this change affect user-facing APIs or examples documented on http://prebid.org?

## Description of change
PBS has an ability now to reuse server bidding adapter code, ak "server adapter alias". 
Consider following case e.g Mediafuse: 
1) Server adapter Mediafuse is an alias of adtelligent, defines its own bidding urls. https://github.com/prebid/prebid-server/pull/1635/files
2) And it also has prebid.js alias. 
3) Prebid.js bundle is built with parent adapter (e.g Adtelligent) and prebidServerBidAdapter

In this case, bid request sent to PBS includes ext   telling  mediafuse is alias of adtelligent, and this ext  forcing PBS to bid from Adtelligent adapter instead of Mediafuse. 

This feature tells prebidServerBidAdapter to skip PBS aliasing for those aliases who support PBS to bid through correct adapter builder, and return correct cookie sync url. 

## Examples
Prerequisites: run PBS locally. With Mediafuse [changes](https://github.com/prebid/prebid-server/pull/1635/files)  
Master: 
:white_check_mark: [prebidServerBidAdapter](http://player.adtcdn.com/examples/master-pbs.html)  pbjs has no clue about adtelligent and aliases so it sends straight to mediafuse.
:x: [prebidServerBidAdapter + adtelligentBidAdapter](http://player.adtcdn.com/examples/master-pbs-adt.html)  - **adtelligent adapter processing**

Feature:
:white_check_mark: [prebidServerBidAdapter](http://player.adtcdn.com/examples/feature-pbs.html) - mediafuse adapter processing (nothing changed)
:white_check_mark: [prebidServerBidAdapter + adtelligentBidAdapter](http://player.adtcdn.com/examples/feature-pbs-adt.html)  - mediafuse adapter processing
:white_check_mark: [prebidServerBidAdapter + adtelligentBidAdapter  & selectmedia req](http://player.adtcdn.com/examples/feature-pbs-adt-other.html) - adtelligent adapter processing

- g.moroz@atelligent.com
- [x] official adapter submission

Related PR: https://github.com/prebid/prebid-server/pull/1635/files

2021-01-07 15:19 UTC, Fawke requested changes
Hi @GeneGenie,

Thanks for the PR, this change looks good. 

Although there's not an API change for publisher, but for adapter creators, can you add a note to the docs telling them about the new prop, `skipPbsAliasing`. I guess adding the docs [here](https://docs.prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter) makes sense. Adding @bretg for suggestions if he has any better place to document this.

Also, can you add some unit test for the two files? `prebidServerBidAdapter_spec.js` and `bidderFactory.js`

2021-01-07 18:28 UTC, robertrmartinez requested changes
This is an interesting use case, and a great solution!

Looks good, but as @Fawke mentions, please add unit tests!

2021-01-11 15:38 UTC, GeneGenie commented
Thanks for review, will do asap

2021-01-11 20:00 UTC, GeneGenie commented
@robertrmartinez  tests added, doc added (not sure about its quality)

2021-01-12 15:21 UTC, robertrmartinez approved these changes
lgtm

2021-01-12 16:03 UTC, robertrmartinez commented
@GeneGenie Looks fine, but can you update your branch with latest master?

2021-01-13 17:36 UTC, smenzer commented
@Fawke and @robertrmartinez looks like tests were added and circleci tests are passing ... if you're good with this one can you please merge, otherwise let @GeneGenie know what else is missing? thanks!

2021-01-15 09:27 UTC, Fawke approved these changes
LGTM

2021-01-15 09:31 UTC, merged