Add UserId Submodule AdmixerId
prebid/Prebid.js pull request #6238
Opened 2021-01-28 12:10 UTC by Galphimbl

## Type of change

- [x] Feature
- [x] Does this change affect user-facing APIs or examples documented on http://prebid.org?

## Description of change

Adds AdmixerId System to the user id module

prebid.github.io PR [#2666](https://github.com/prebid/prebid.github.io/pull/2666)

2021-02-02 15:34 UTC, jdwieland8282 commented
Docs PR https://github.com/prebid/prebid.github.io/pull/2666

2021-03-05 11:09 UTC, smenzer commented
@jlukas79 have you had a chance to review this yet?

2021-03-29 18:01 UTC, patmmccann approved these changes
Code mostly looks good, only one change I can see:

2021-03-29 18:04 UTC, patmmccann requested changes

2021-03-29 18:04 UTC, patmmccann commented on modules/userId/eids.js
> +    atype: 1
aren't you agent type 3?

2021-03-29 20:09 UTC, patmmccann commented
@Galphimbl can you also resolve conflicts?

2021-03-29 22:00 UTC, smenzer requested changes
I still need to do a deeper review but these were two obvious things for me

2021-03-29 22:00 UTC, smenzer commented on modules/admixerIdSystem.js
> +    return { '__adm__admixer': value }
This is the value that gets exposed to bidder adapters...to follow standards it should be `admixerId`

2021-03-29 22:00 UTC, smenzer commented on modules/userId/eids.js
> +  '__adm__admixer': {
Following convention this should be `admixerId`

2021-03-30 08:04 UTC, smenzer requested changes
finished doing a full review...code looks good with the minor comments I made.

you should also add tests to `userId_spec.js` to ensure full coverage.

2021-04-06 07:59 UTC, Galphimbl commented
@smenzer @patmmccann upd

2021-04-06 08:09 UTC, smenzer commented
@Galphimbl changes look good. I would suggest doing a rebase on master since it looks like you've pulled in some other commits and I just want to make sure this is a clean PR (I see some "new" code from UID and Novatiq, for example, which is already in the PBJS master).

2021-04-06 08:18 UTC, Galphimbl commented
@smenzer i've just merge master into PR and resolve conflicts.

2021-04-06 08:49 UTC, patmmccann approved these changes

2021-04-06 09:02 UTC, smenzer approved these changes
LGTM

2021-04-06 09:03 UTC, merged