smartxBidAdapter: new Feature - Made Out-Stream Player configurable
prebid/Prebid.js pull request #6239
Opened 2021-01-29 11:30 UTC by Skylinar

## Type of change

- [X] Feature
- [X] Code style update (formatting, local variables)

## Description of change

Made Out-Stream Player configurable

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

2021-02-03 04:23 UTC, harpere requested changes
Your tests are failing

2021-02-03 09:57 UTC, Skylinar commented
Hi @harpere, should be good now.

2021-02-03 11:26 UTC, Skylinar reviewed
fixed

2021-02-04 06:34 UTC, harpere approved these changes

2021-02-04 06:34 UTC, merged