Update ttl outstream
prebid/Prebid.js pull request #6253
Opened 2021-02-01 21:47 UTC by stevealliance

## Type of change

- [ x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Condition to remove ttl change in vast validation condition

2021-02-03 05:32 UTC, harpere requested changes
please remove the `package-lock.json` file from the PR

2021-02-03 05:32 UTC, harpere commented on modules/districtmDMXBidAdapter.js
> +// import { INSTREAM, OUTSTREAM } from '../src/video.js';
you want to keep these here commented?

2021-02-04 21:30 UTC, harpere commented
@stevealliance - please see comments above

2021-02-10 16:03 UTC, harpere requested changes
Please don't DELETE `package-lock.json`.  I just wanted your changes to it removed from the PR.

2021-02-10 16:03 UTC, harpere commented on modules/districtmDMXBidAdapter.js
> +              if (nBid.mediaType && nBid.mediaType === 'video') {
not a big deal, but just noticed that this could just be
```if (nBid.mediaType === 'video') {```
don't need the `nBid.mediaType` part first.

2021-02-11 21:33 UTC, stevealliance commented on modules/districtmDMXBidAdapter.js
> +// import { INSTREAM, OUTSTREAM } from '../src/video.js';
Removed comments from PR

2021-02-16 14:14 UTC, stevealliance commented
@harpere did you have time to look at this PR

2021-02-16 17:01 UTC, harpere approved these changes

2021-02-16 17:01 UTC, merged