Zeotap id plus gvlid
prebid/Prebid.js pull request #6260
Opened 2021-02-02 19:56 UTC by shikharsharma-zeotap

## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Added **gvlid** as Zeotap's vendor id to avoid issues in case **gdprEnforcement** module is enabled. 
Also pass appropriate arguments to StorageManager (gvlid, module name).

## Desired Output
Prebid is able to fetch Zeotap cookie (IDP) from the storage and `pbjs.getUserIds()` gives appropriate results.

## Actual Result
Currently since the gvlid was not set, so warning of _'User denied Permission .. '_ was seen on dev console if gdprEnforcement is enabled. Also since storageManager was not invoked with correct arguments, cookie was not read from storage even after adding _'zeotapIdPlus'_ to _vendorExceptions_ in `prebid.setConfig()` on publisher page.

2021-02-03 06:06 UTC, harpere requested changes
why not add some tests, especially since there was a bug that might have been caught.

2021-02-03 13:19 UTC, shikharsharma-zeotap commented
@harpere I have added some unit tests to zeotap Id module.

2021-02-04 06:59 UTC, harpere commented
@shikharsharma-zeotap thanks for adding the tests.  This new test failure should also have been fixed in master.  Please pull in the latest master so we can rerun the tests.  Thanks.

2021-02-04 07:30 UTC, shikharsharma-zeotap commented
Pulled in the latest master @harpere

2021-02-04 08:34 UTC, shikharsharma-zeotap commented
@harpere CircleCI looks green now.

2021-02-04 21:31 UTC, harpere approved these changes

2021-02-04 21:31 UTC, merged