Update adWMG adapter - add new parameter, fix minor bugs
prebid/Prebid.js pull request #6265
Opened 2021-02-03 14:08 UTC by nyakove

## Type of change

- [x] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Add new bid parameter - 'floorCPM'
Fix minor bugs in user sync

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2021-02-03 14:12 UTC, nyakove commented
docs PR: https://github.com/prebid/prebid.github.io/pull/2683

2021-02-04 07:07 UTC, harpere requested changes
I'd recommend adding some tests to verify your changes.

2021-02-04 07:07 UTC, harpere commented on modules/adWMGBidAdapter.js
> +    if (gdprConsent && !SYNC_ENDPOINT.includes('gdpr')) {
this is causing tests to fail because `.includes()` is not supported in `IE11`

2021-02-04 09:51 UTC, nyakove commented
Hi @harpere! Thanks for review. I've made some changes (use _.indexOf_ instead of _.includes_ for compatibility with IE11) and add unit tests to cover code changes.

As about new param 'floorCPM', it is non-required and passes as is in _params_ object here:
`bids: {
          bidder: bidRequest.bidder,
          **params: bidRequest.params**
        },`
        
Because it's non-required, I do not check it in adapter's code

2021-02-04 21:38 UTC, harpere approved these changes

2021-02-04 21:39 UTC, merged