Fpd 2.0 Update
prebid/Prebid.js pull request #6293
Opened 2021-02-10 12:28 UTC by mmoschovas

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [X ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

DETAIL:
Prebid's First Party Data (FPD) convention revision with backwards compatibility. 

MODULES UPDATED:
gptPreAuction, prebidServer, admixer, adrelevantis, amx, avocet, criteo, grid, haloRtd, imar, jwPlayerRtd, luponmedia, rubicon, smaato, triplelift

BACKWARD COMPATIBILITY GLOBAL/BIDDER:
fpd.context.ATTR --> ortb2.site.ATTR
fpd.context.data.ATTR --> ortb2.site.ext.data
fpd.user.ATTR --> ortb2.user.ATTR
fpd.user.data.ATTR --> ortb2.user.ext.data. (for fpd only... ortb2 can specify user.data)

BACKWARD COMPATIBILITY ADUNIT:
AdUnit.fpd - > AdUnit.ortb2Imp
AdUnit.fpd.context.ATTR -> AdUnit.ortb2Imp.ext.data.ATTR

ISSUE:
https://github.com/prebid/Prebid.js/issues/5795

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2021-02-10 19:17 UTC, bretg commented
@anthonylauzon - halo is the only module not in this PR... what you're doing wasn't clear to us. Happy to sit with someone on your team to describe generally what needs to be done so you guys can make the appropriate changes. 

I'll be reaching out via email to as many of the affected parties as I can find addresses for so they can confirm and do any additional testing. In the meantime, here's a list of github handles that have recently touched affected modules

admixer @AdmixerTech
amx @nickjacob
avocet @scritchley
inmar @zandree-owneriq
criteo @leonardlabat , @allanjun
grid @TheMediaGrid
luponmedia @adxpremium
smaato @sbrosinski
triplelift @kzhouTL , @colbertk , @davidwoodsandersen

2021-02-10 21:23 UTC, anthonylauzon commented
@bretg i will pull this branch and do what i can to update our module to meet the new spec. we'll set up a call if there are any issues requiring discussion.  i'll request you as a reviewer when that's complete.

2021-02-10 21:44 UTC, bretg commented
I've sent direct email to: admixer, adrelevantis, amx, avocet, criteo, grid, inmar, jwplayer, luponmedia, smaato, and triplelift.

2021-02-11 08:19 UTC, leonardlabat commented
Hello @bretg 
It looks ok for the criteo adapter 👍 
Thanks for the change

2021-02-11 14:42 UTC, AdmixerTech commented
Hi @bretg 
looks good for admixer adapter
thanks

2021-02-11 19:00 UTC, karimMourra commented on src/prebid.js
> +/** ƒ
nit: typo

2021-02-11 19:09 UTC, mmoschovas commented on src/prebid.js
> +/** ƒ
Remove this. Thanks for catching

2021-02-11 20:14 UTC, karimMourra approved these changes
Approving changes made to the JW Player RTD module! Thank you so much for the update!

2021-02-15 07:42 UTC, TheMediaGrid approved these changes

2021-02-15 09:23 UTC, Enigo commented
Approving changes made to the **Smaato** module.
thanks, guys, we will remove the legacy code soon.

2021-02-16 22:49 UTC, bretg commented
@musikele - Jason won't be able to get to this until next week. The other reviewers only verified their individual adapter changes. Could you take a look at the PBS-core, gptPreAuction, pbsBidAdapter, and Rubicon changes here?

2021-02-18 03:57 UTC, anthonylauzon commented
As noted in https://github.com/prebid/Prebid.js/issues/5795, I am not seeing how it is possible to add dynamic segment information for users within the ortb object defined by setConfig.  I can add this data at an ad unit level, but this would result in duplication and the bid adapters might not be looking for it.

2021-02-18 21:05 UTC, bretg commented
@anthonylauzon - I agree that the setConfig interface is awkward for RTD modules.

In the short term, the suggestion is that the RTD module calls getConfig({ortb2}), updates the output, and then calls setConfig({ortb2}).

I don't know how to handle bidder-sensitivity here. 
1) I suspect we're going to need to extend the 'eidPermissions' feature to 'rtdPermissions'
2) I don't think setBidderConfig() will handle "merging" multiple configs properly, so an initial hack may be needed.

2021-02-24 21:55 UTC, bretg commented
docs PR https://github.com/prebid/prebid.github.io/pull/2722

2021-03-03 15:02 UTC, jsnellbaker requested changes
Hi @mmoschovas 

Thanks for putting everything together.  I think the core changes are mostly in good shape.  There was one potential issue I observed during testing; details below:

Supplied value:
```
      pbjs.setConfig({
        ortb2: {
          site: {
            name: 'example-name',
            domain: 'page.example.com',
            cat: ['IAB2'],
            sectioncat: ["IAB2-2"],
            pagecat: ["IAB2-2"],
            page: "https://page.example.com/here.html",
            ref: "https://ref.example.com",
            keywords: 'power tools, drills',
            search: 'drill',
            content: { userrating: 4 },
            ext: {
              data: {
                pageType: 'article',
                category: 'repair'
              }
            }
          },
          user: {
            yob: 1945,
            gender: 'm',
            keywords: 'a,b',
            data: [{
              name: 'dataprovider.com',
              ext: { taxonomyname: 'IAB' },
              segment: [{
                id: '1'
              }]
            }],
            ext: {
              data: {
                registered: true,
                interests: ['cars']
              }
            }
          }
        }
      });
```
converted value from config.getLegacyFpd():
```
{
  "context": {
    "name": "example-name",
    "domain": "page.example.com",
    "cat": [
      "IAB2"
    ],
    "sectioncat": [
      "IAB2-2"
    ],
    "pagecat": [
      "IAB2-2"
    ],
    "page": "https://page.example.com/here.html",
    "ref": "https://ref.example.com",
    "keywords": "power tools, drills",
    "search": "drill",
    "content": {
      "userrating": 4
    },
    "data": {
      "pageType": "article",
      "category": "repair"
    }
  },
  "user": {
    "yob": 1945,
    "gender": "m",
    "keywords": "a,b",
    "data": [
      {
        "name": "dataprovider.com",
        "ext": {
          "taxonomyname": "IAB"
        },
        "segment": [
          {
            "id": "1"
          }
        ]
      }
    ]
  }
}
```

If you look at the results in the legacy converted user object, it populated the 'old' `data` field from the `ortb2.user.data` array field rather than `ortb2.user.ext.data` (which was the old `fpd.user.data` field).

The conversion works fine if your setConfig uses the fpd setup and the code converts it forward and then backward.  This is likely b/c of the shared name `data` wasn't in the fpd construct.  

Can you please take a look into this?  I think based on what we discussed the other day, we need to fix this behavior.

Please let me know if you have questions about the above. Thanks!

2021-03-03 20:20 UTC, bretg commented
Good catch @jsnellbaker - I didn't test config.getLegacyFpd() - hopefully pretty easy fix @mmoschovas ?

2021-03-04 04:31 UTC, ncolletti reviewed
This looks good so far @mmoschovas, nice work. Only have a few small comments from a first pass, will go over more with tests tomorrow.

2021-03-04 18:23 UTC, mmoschovas commented
Thanks for reviewing @jsnellbaker and @ncolletti. Just pushed changes that should cover the above requests

2021-03-05 02:30 UTC, ncolletti approved these changes
LGTM

2021-03-05 17:36 UTC, jsnellbaker approved these changes
@mmoschovas  I think this looks good now; thanks for making the fix.

@bretg Are there any more reviews we're waiting on from the bidders who are being updated?  Or should we be free to merge?

2021-03-05 17:48 UTC, ncolletti commented
Noticed the PR_REVIEW markdown references fpd.context and fpd.user, may want to update that here.

2021-03-05 22:51 UTC, bretg commented
Great news. Ok, I've upgraded this to a "feature", and plan to modify the release notes to point to the First Party Data page. 

Merging.

2021-03-05 22:51 UTC, merged