Smartyads Bid Adapter: add coppa field from config
prebid/Prebid.js pull request #6402
Opened 2021-03-10 13:44 UTC by SmartyAdsSSP

## Type of change
- [ x] Feature

## Description of change

Add coppa field from config

- test parameters for validating bids
```
var adUnits = [
                // Will return static native ad. Assets are stored through user UI for each placement separetly
                {
                    code: 'placementId_0',
                    mediaTypes: {
                        native: {}
                    },
                    bids: [
                        {
                            bidder: 'smartyads',
                            params: {
                                placementId: 0,
                                traffic: 'native'
                            }
                        }
                    ]
                },
                // Will return static test banner
                {
                    code: 'placementId_0',
                    mediaTypes: {
                        video: {
                            sizes: [[300, 250]],
                        }
                    },
                    bids: [
                        {
                            bidder: 'smartyads',
                            params: {
                                placementId: 0,
                                traffic: 'video'
                            }
                        }
                    ]
                },
                // Will return test vast xml. All video params are stored under placement in publishers UI
                {
                    code: 'placementId_0',
                    mediaTypes: {
                        banner: {
                            sizes: [[300, 250]],
                        }
                    },
                    bids: [
                        {
                            bidder: 'smartyads',
                            params: {
                                placementId: 0,
                                traffic: 'banner'
                            }
                        }
                    ]
                }
            ];
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- support@smartyads.com
- [x ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2021-03-11 00:04 UTC, robertrmartinez requested changes
Other than the minor test update looks good.

2021-03-11 00:04 UTC, robertrmartinez commented on test/spec/modules/smartyadsBidAdapter_spec.js
> +        .returns(true);
It is a better idea to set your stubs in beforeEach and reset them in afterEach.

If for some reason your test fails before the `config.getConfig.restore();` then the next adapter tests which run will have this stubbed still which can cause flakey failures.

2021-03-15 09:53 UTC, SmartyAdsSSP commented
Hello, @robertrmartinez ! Did you have chance to review my fixes?

2021-03-17 15:27 UTC, robertrmartinez approved these changes
thanks for the update!

Approved, waiting second review

2021-03-17 17:35 UTC, merged