add new params to ironsource adapter
prebid/Prebid.js pull request #6408
Opened 2021-03-11 18:58 UTC by lasloche

## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Add isWrapper and sessionId as adapter parameters.

2021-03-12 17:33 UTC, robertrmartinez requested changes
Same as other PR, add a unit test.

Also, could these two bid adapters be one single one and just aliases of each other?

2021-03-15 09:42 UTC, lasloche commented
> Same as other PR, add a unit test.

Hi, I've added a unit test for each of the new params.

> Also, could these two bid adapters be one single one and just aliases of each other?

We are currently in a migration process, so we need to update both of the adapters separately until it's done.

2021-03-15 14:22 UTC, ChrisHuie approved these changes

2021-03-15 14:22 UTC, ChrisHuie approved these changes

2021-03-15 14:25 UTC, merged