Add referer detection for Qwarry bid adapter
prebid/Prebid.js pull request #6412
Opened 2021-03-12 12:49 UTC by pro-nsk

## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Add referer detection for Qwarry bid adapter

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission
abogdanov@asteriosoft.com

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2021-03-12 17:38 UTC, robertrmartinez requested changes
refererInfo comes inside the bidRequest already.

There is no need to run the function yourself.

`bidderRequest.refererInfo`

2021-03-15 05:10 UTC, pro-nsk commented
> 
> 
> refererInfo comes inside the bidRequest already.
> 
> There is no need to run the function yourself.
> 
> `bidderRequest.refererInfo`

Thanks. Changed.

2021-03-17 15:28 UTC, robertrmartinez approved these changes

2021-03-17 17:24 UTC, ChrisHuie approved these changes

2021-03-17 17:25 UTC, merged