Add video context:outstream handling
prebid/Prebid.js pull request #6458
Opened 2021-03-23 11:30 UTC by lunamedia

## Type of change

- [x] Feature

## Description of change
Allow publishers to set context:outstream for video demand to get vastXml response.

2021-03-24 15:13 UTC, patmmccann commented
Please see also #6466

2021-03-26 11:26 UTC, mmoschovas requested changes

2021-03-26 11:26 UTC, mmoschovas commented on modules/lunamediahbBidAdapter.js
> +          placement.wPlayer = mediaType[VIDEO].playerSize[0];
Prebid nests the playerSize array that is defined in the ad unit, meaning that [640, 480] is converted to [[640,480]]. So currently, you will only be passing an array through placement.wPlayer and placement.hPlayer is undefined and therefore dropped. I believe you are trying to pass the individual number values of the playerSize through their respective properties, so you will need to look into the second array in order to do so.

```
placement.wPlayer = mediaType[VIDEO].playerSize[0][0];
placement.hPlayer = mediaType[VIDEO].playerSize[0][1];
```

2021-04-14 13:16 UTC, ChrisHuie commented
@lunamedia following up on the above reviewer comment for this pr and also issue #6466 

Let me know if I can help on this pr.

2021-04-15 15:47 UTC, lunamedia commented
Chris,

Thanks for the note. We will look into this and get back to you!

On Wed, Apr 14, 2021 at 9:16 AM Chris Huie ***@***.***> wrote:

> @lunamedia <https://github.com/lunamedia> following up on the above
> reviewer comment for this pr and also issue #6466
> <https://github.com/prebid/Prebid.js/issues/6466>
>
> Let me know if I can help on this pr.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/prebid/Prebid.js/pull/6458#issuecomment-819510286>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARRFG3JGOMLZNBTLY65DM53TIWIUPANCNFSM4ZU7SS6A>
> .
>

2021-06-04 17:12 UTC, patmmccann commented
please note that the old lunamedia adapter is in violation of #6512 and won't be ported to prebid 5 currently. Is this lunamedia hb your new adapter and the old one is deprecated?

2021-06-04 17:53 UTC, lunamedia commented
Hi Patrick,

We are fine to deprecate it but we are transitioning a few clients over.
Can we keep it up for a little bit and confirm once all clients are off it?

On Fri, Jun 4, 2021 at 1:12 PM Patrick McCann ***@***.***>
wrote:

> please note that the old lunamedia adapter is in violation of #6512
> <https://github.com/prebid/Prebid.js/issues/6512> and won't be ported to
> prebid 5 currently. Is this lunamedia hb your new adapter and the old one
> is deprecated?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/prebid/Prebid.js/pull/6458#issuecomment-854882858>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARRFG3MKPWYTXMDHMOVORO3TRECQBANCNFSM4ZU7SS6A>
> .
>

2021-06-04 18:01 UTC, patmmccann commented
Please also fix #6650 for luna hb on this PR. 

Advise your clients to transition to Luna HB on or before their upgrade to Prebid 5. Your adapter won't stop working unless your clients upgrade to Prebid 5

2021-11-15 12:23 UTC, ChrisHuie commented
@lunamedia This pr has been outstanding for a while. Is this still being worked on? We are cleaning out old prs so if I don't hear back on this by Thanksgiving will close and you can reopen when needed.

2021-11-16 15:46 UTC, lunamedia commented
Hi Chris,

Adding @Daniel Cohen ***@***.***> and @Mary Drachova
***@***.***> who manage the operation at Luna Media.
We will get back to you as soon as possible

Best,
John

On Mon, Nov 15, 2021 at 2:23 PM Chris Huie ***@***.***> wrote:

> @lunamedia <https://github.com/lunamedia> This pr has been outstanding
> for a while. Is this still being worked on? We are cleaning out old prs so
> if I don't hear back on this by Thanksgiving will close and you can reopen
> when needed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/prebid/Prebid.js/pull/6458#issuecomment-968859208>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARRFG3PDOPWRWECHJCHNXBTUMD3T3ANCNFSM4ZU7SS6A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-30 22:27 UTC, closed without merging