Updating merkle user id module
prebid/Prebid.js pull request #6503
Opened 2021-03-30 20:21 UTC by SKOCHERI

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2021-03-31 09:17 UTC, smenzer requested changes
generally looks good, with one comment below.

also needs a docs PR since there are publisher-facing changes here. this is also a breaking change for publishers since there are new values that are required now...should this move to the 5.0 branch?

2021-03-31 09:17 UTC, smenzer commented on modules/merkleIdSystem.js
> +    url.append(`?sv_session=${session}`);
i think this start with an `&` and not a `?` since it's not the first querystring param in the list

2021-03-31 16:17 UTC, angelamerkelprebid commented
My reign is over

2021-03-31 16:22 UTC, jdwieland8282 commented
Spoke with @angelamerkelprebid in the 3/31 pbjs PMC.   This module was originally built by an external party.  This is not an official userid sub adapter, merkle does not intend for their module to work this way.  This PR represents the changes Merkle has requested be made.

2021-03-31 16:36 UTC, smenzer commented
thanks @jdwieland8282 very helpful context.

2021-03-31 16:38 UTC, smenzer approved these changes
LGTM

just needs docs

2021-03-31 20:47 UTC, patmmccann approved these changes

2021-04-02 22:26 UTC, jdwieland8282 commented
docs pr https://github.com/prebid/prebid.github.io/pull/2822

2021-04-03 11:47 UTC, merged