adomain support
prebid/Prebid.js pull request #6595
Opened 2021-04-15 11:29 UTC by mjaworskiccx

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2021-04-15 12:46 UTC, patmmccann requested changes

2021-04-15 12:46 UTC, patmmccann commented on modules/ccxBidAdapter.js
> +    advertiserDomains: bid.adomain || []
Meta.advertiserDomains please

2021-04-15 13:25 UTC, mjaworskiccx commented
added

2021-04-19 18:39 UTC, robertrmartinez commented
please add a unit test!

2021-04-20 18:20 UTC, patmmccann commented
@mjaworskiccx here is an example of a unit test for this change: https://github.com/prebid/Prebid.js/pull/6495/files

2021-04-21 09:34 UTC, mjaworskiccx commented
@patmmccann thx, unit test added

2021-04-22 17:46 UTC, robertrmartinez commented
Looks good, assigning to @patmmccann for re-review

2021-04-23 11:25 UTC, merged