SharedId & PubcommonId: CCPA and COPPA support
prebid/Prebid.js pull request #6632
Opened 2021-04-20 19:42 UTC by SKOCHERI

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2021-04-20 19:44 UTC, SKOCHERI commented
This PR is for https://github.com/prebid/Prebid.js/issues/6433

2021-04-28 09:43 UTC, smenzer requested changes
This implementation means that we're now sending consent data twice to id modules, which I don't think is the right approach.  usp and coppa are both already available to id modules by requesting them (rather than be passed in as arguments).  if they must be passed in as arguments, then we should replace the existing consentData with the proposed new object that contains ALL consent data.

2021-04-28 21:46 UTC, SKOCHERI commented
> This implementation means that we're now sending consent data twice to id modules, which I don't think is the right approach. usp and coppa are both already available to id modules by requesting them (rather than be passed in as arguments). if they must be passed in as arguments, then we should replace the existing consentData with the proposed new object that contains ALL consent data.

@smenzer Agree that we will have duplicate consent data as argument. Updating the module to  get consent within the module. For coppa, which is in the config and the user id submodules can have access to only the submodule config (as a argument) hence updating the adapterManger.js to get the coppa from the config

2021-04-29 07:21 UTC, smenzer commented
> @smenzer Agree that we will have duplicate consent data as argument. Updating the module to get consent within the module. For coppa, which is in the config and the user id submodules can have access to only the submodule config (as a argument) hence updating the adapterManger.js to get the coppa from the config

This looks much cleaner, thank you!

2021-04-29 07:34 UTC, smenzer requested changes
can you please add tests for the new `getCoppa()` handler?

2021-04-29 07:34 UTC, smenzer commented on modules/pubCommonIdSystem.js
> +      utils.logInfo('PubCommonId: coppa not provided, exiting PubCommonId');
should this say "coppa not supported" or "IDs not provided for coppa requests"? to me, this message sounds like "coppa config wasn't provided, so we're existing"

2021-04-29 07:34 UTC, smenzer commented on modules/pubCommonIdSystem.js
> +      utils.logInfo('PubCommonId: coppa not provided, exiting PubCommonId');
same comment as above

2021-04-29 07:34 UTC, smenzer commented on modules/sharedIdSystem.js
> +      utils.logInfo('SharedId: coppa not provided, exiting SharedId');
ditto

2021-04-29 07:34 UTC, smenzer commented on modules/sharedIdSystem.js
> +      utils.logInfo('SharedId: coppa not provided, exiting SharedId');
ditto

2021-04-29 07:34 UTC, smenzer commented on modules/userId/index.js
> -  * @typedef {Object} RefreshUserIdsOptions
this whole file just seems like whitespace changes now...can you just revert them all since there's no functional change?

2021-04-30 07:01 UTC, smenzer approved these changes
Thanks for the updates @SKOCHERI ! LGTM

2021-05-03 15:00 UTC, jsnellbaker commented
As a temporary measure (see https://github.com/prebid/Prebid.js/pull/6632#issuecomment-828999753), these changes LGTM

2021-05-03 15:02 UTC, merged