Prebid Core: Readme.md import name change
prebid/Prebid.js pull request #6638
Opened 2021-04-21 16:50 UTC by patmmccann

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [X] Build related changes
- [ ] CI related changes
- [X] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Imports Prebid as pbjs instead of prebid to match other examples. Issue noted on #5287

2021-04-21 18:29 UTC, snapwich requested changes
you missed some spots.

prebid.processQueue and prebid.requestBids in the following lines would also need to be updated.

2021-04-21 19:19 UTC, patmmccann commented
thank you

2021-04-21 21:13 UTC, snapwich approved these changes
LGTM

2021-04-22 11:12 UTC, ChrisHuie approved these changes

2021-04-22 11:12 UTC, merged