TheMediaGrid Bid Adapter: Coppa support
prebid/Prebid.js pull request #6655
Opened 2021-04-26 16:46 UTC by TheMediaGrid

## Type of change

- [x] Feature

## Description of change

Added coppa support

- grid-tech@themediagrid.com
- [x] official adapter submission

- A link to a PR on the docs repo https://github.com/prebid/prebid.github.io/pull/2901

2021-04-26 22:44 UTC, patmmccann commented
This appears to be based off #6609 

Can you make this its own PR or close #6609?

2021-04-27 04:07 UTC, harpere requested changes
LGTM, but please fix merge conflict.

2021-04-27 09:40 UTC, TheMediaGrid commented
Done

2021-04-28 16:47 UTC, harpere approved these changes

2021-04-28 16:48 UTC, merged