Reset digital
prebid/Prebid.js pull request #6710
Opened 2021-05-06 02:06 UTC by evanmsmrtb

## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: 'resetdigital',
  params: {
    pubId: '123',
    forceBid: true
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2021-05-12 16:39 UTC, mmoschovas requested changes

2021-05-12 16:39 UTC, mmoschovas commented on modules/resetdigitalBidAdapter.js
> +    return (bid.params.pubId !== null || bid.params.zoneId !== null);
This logic is specifically looking for null values, but not defining either of these params would result in undefined which passes this check and allows the ad units bid request. Can this be updated to check for all empty values?

2021-05-12 16:39 UTC, mmoschovas commented on modules/resetdigitalBidAdapter.js
> +      bidderRequest.refererInfo.stack ? bidderRequest.refererInfo
I think the value if the condition proves true was meant to be bidderRequest.refererInfo.stack, no?

2021-05-12 17:45 UTC, mmoschovas commented
@evanmsmrtb Also will need docs PR for this bidder

2021-05-19 10:25 UTC, mmoschovas approved these changes
Thanks for making the changes. LGTM

2021-05-20 05:05 UTC, patmmccann requested changes
You must return advertiserDomains

2021-05-20 05:06 UTC, patmmccann commented on modules/resetdigitalBidAdapter.js
> +function getDomain () {
Why aren't you using built in functions for this

2021-06-01 19:21 UTC, mmoschovas commented
@evanmsmrtb can you please resolve lint errors on this?

2021-06-02 13:31 UTC, mmoschovas commented
@evanmsmrtb also Patrick's comment regarding advertiserDomains needs to be addressed as well before we can move forward with this

2021-06-03 17:46 UTC, bretg commented
docs PR https://github.com/prebid/prebid.github.io/pull/2967

2021-06-10 12:28 UTC, patmmccann approved these changes

2021-06-10 12:28 UTC, merged