add support meta.advertiserDomains, add sample adunit, validate dealId
prebid/Prebid.js pull request #6711
Opened 2021-05-06 02:59 UTC by thuyhq

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

## Description of change
- Add meta.advertiserDomains to Apacdex bid adapter according to the issue mentioned https://github.com/prebid/Prebid.js/issues/6650
- Add and update sample ad units
- Validate dealId from server response
- Lint code

2021-05-06 15:47 UTC, thuyhq commented
Hello @ChrisHuie,
Looks like the error from circleCI is not coming from my code. What do I need to do to bypass it?
Thanks very much!

2021-05-06 15:52 UTC, patmmccann commented
Remerge master, #6706 should help

2021-05-06 15:53 UTC, patmmccann requested changes

2021-05-06 15:53 UTC, patmmccann commented on modules/apacdexBidAdapter.md
> +      ... // Aditional ORTB video params
spelling

2021-05-06 15:53 UTC, patmmccann commented on modules/apacdexBidAdapter.md
> +        floorPrice: 0.01, // default is 0.01 if not declared
not mentioned in your js.

2021-05-06 15:53 UTC, patmmccann commented on modules/apacdexBidAdapter.md
> +        floorPrice: 0.01, // default is 0.01 if not declared
not in the js

2021-05-06 15:54 UTC, patmmccann commented on modules/apacdexBidAdapter.md
> +        floorPrice: 0.01, // default is 0.01 if not declared
if you plan to add it, please note #6465

2021-05-26 21:03 UTC, thuyhq commented
Hello @patmmccann,
When will my PR be merged?
Is there anything I can do right now?

2021-05-27 11:40 UTC, merged

2021-05-27 11:40 UTC, patmmccann reviewed
Lgtm