New Adapter: BidsCube
prebid/Prebid.js pull request #6730
Opened 2021-05-10 13:30 UTC by vlaktion

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2021-05-10 21:17 UTC, msm0504 requested changes

2021-05-10 21:41 UTC, bretg commented
docs PR https://github.com/prebid/prebid.github.io/pull/2944

2021-05-11 07:36 UTC, vlaktion commented on modules/bidscubeBidAdapter.js
> +const URL = 'https://supply.bidscube.com/?c=o&m=multi'
We will deploy our server application after the adapter has been approved.

2021-05-11 10:11 UTC, vlaktion commented
All done

2021-05-18 08:46 UTC, vlaktion commented on modules/bidscubeBidAdapter.js
> +const URL = 'https://supply.bidscube.com/?c=o&m=multi'
We deployed the server and it works

2021-05-18 08:46 UTC, vlaktion commented on modules/bidscubeBidAdapter.md
> +                            placementId: 0,
We deployed the server and it works. Can you approve commits?

2021-05-20 04:56 UTC, patmmccann requested changes
You must return advertiserDomains

2021-05-20 21:38 UTC, msm0504 commented on modules/bidscubeBidAdapter.js
> +const URL = 'https://supply.bidscube.com/?c=o&m=multi'
I'm still seeing the same error for `https://supply.bidscube.com`

2021-05-26 12:54 UTC, vlaktion commented on modules/bidscubeBidAdapter.js
> +const URL = 'https://supply.bidscube.com/?c=o&m=multi'
It needs a parameter. For example https://supply.bidscube.com/?c=o&m=multi

2021-05-26 12:57 UTC, vlaktion commented on modules/bidscubeBidAdapter.js
> +const URL = 'https://supply.bidscube.com/?c=o&m=multi'
And POST method with example payload
{
    "bidId": "9ec5b177515ee2e5",
    "bidder": "bidscube",
    "placements": [{
      "placementId": 0,
      "traffic": "banner",
      "allParams": "{}"
    }]
}

2021-05-26 12:59 UTC, vlaktion commented on modules/bidscubeBidAdapter.js
> +const URL = 'https://supply.bidscube.com/?c=o&m=multi'
You can test it throw Postman

2021-05-26 18:45 UTC, msm0504 commented on modules/bidscubeBidAdapter.js
> +const URL = 'https://supply.bidscube.com/?c=o&m=multi'
@vlaktion When I try using a local test page, I'm now seeing this error:
```
Access to XMLHttpRequest at 'https://supply.bidscube.com/?c=o&m=multi' from origin 'http://localhost:3000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://localhost' that is not equal to the supplied origin.
```

2021-05-27 07:51 UTC, vlaktion commented on modules/bidscubeBidAdapter.js
> +const URL = 'https://supply.bidscube.com/?c=o&m=multi'
Fixed this problem

2021-05-27 11:10 UTC, patmmccann commented
@vlaktion reminder that you must return advertiserDomains, see #6650 for reference

2021-05-28 06:55 UTC, vlaktion commented on modules/bidscubeBidAdapter.js
> +const URL = 'https://supply.bidscube.com/?c=o&m=multi'
Can you approve commits?

2021-06-01 19:23 UTC, msm0504 approved these changes

2021-06-01 19:26 UTC, msm0504 commented
@vlaktion The latest changes allowed me to get data from your server when using my test page. I've approved the PR.

However, before I merge it, please address @patmmccann's comment from last week.

2021-06-02 11:20 UTC, vlaktion commented
@patmmccann I see the advertiserDomains is Optional. I don't have this information. Can you approve my PR?

2021-06-02 16:21 UTC, ChrisHuie commented
@vlaktion it will be required in prebid 5.0 which is being released shortly

2021-06-03 07:20 UTC, vlaktion commented
@patmmccann All done! For test:
POST https://supply.bidscube.com/?c=o&m=multi
{
    "bidId": "9ec5b177515ee2e5",
    "bidder": "bidscube",
    "placements": [{
      "placementId": 0,
      "traffic": "banner",
      "allParams": "{}"
    }]
}

2021-06-03 19:41 UTC, patmmccann commented
Excellent! Can you add a unit test that demonstrates meta.advertiserDomains is set in the interpreted response?

2021-06-04 13:34 UTC, vlaktion commented
@patmmccann Added a unit test that demonstrates meta.advertiserDomains is set in the interpreted response

2021-06-04 15:14 UTC, merged

2021-06-11 11:41 UTC, vlaktion commented
Hi. Why is BidsCube adapter don`t  exist in https://docs.prebid.org/download.html?

2021-06-14 08:29 UTC, vlaktion commented
@patmmccann Hi. Can you answer on my question?