Datablocks Adapter Resubmission
prebid/Prebid.js pull request #6765
Opened 2021-05-14 17:22 UTC by htang555

## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

As per @ChrisHuie in https://github.com/prebid/Prebid.js/issues/6696#issuecomment-841261369

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2021-05-14 17:25 UTC, ChrisHuie commented
Working to figure out how to kick off the CircleCI tests on this pr.

2021-05-18 11:00 UTC, ChrisHuie commented
@htang555 could you give me edit access to this pr to try and manually kick off the tests

2021-05-18 14:10 UTC, htang555 commented
@ChrisHuie just granted you write access to the repo.

2021-05-19 12:27 UTC, ChrisHuie commented
@htang555 I tried to manually kick-off the CircleCi tests but that didn't seem to work. I think merging upstream, in this case, should kick off the CircleCi tests. This is a pretty unique situation so sorry for the back and forth to get this working with our testing setup.

2021-05-19 16:38 UTC, patmmccann commented
Please make sure to add support for meta.advertiserDomains

2021-05-19 16:39 UTC, patmmccann commented on modules/datablocksBidAdapter.js
> +      let resultItem = {requestId: bid.id, cpm: bid.price, creativeId: bid.crid, currency: bid.currency || 'USD', netRevenue: true, ttl: bid.ttl || 360};
meta.advertiserDomains is required

2021-05-20 14:43 UTC, htang555 commented on modules/datablocksBidAdapter.js
> +      let resultItem = {requestId: bid.id, cpm: bid.price, creativeId: bid.crid, currency: bid.currency || 'USD', netRevenue: true, ttl: bid.ttl || 360};
@patmmccann added.

2021-05-20 14:48 UTC, patmmccann commented on modules/datablocksBidAdapter.js
> +      let resultItem = {requestId: bid.id, cpm: bid.price, creativeId: bid.crid, currency: bid.currency || 'USD', netRevenue: true, ttl: bid.ttl || 360};
Tyvm

2021-05-26 15:39 UTC, ChrisHuie commented
I have a follow-up call with CircleCI on this specific pr because everything they told me and I have tried hasn't worked and want to get to the bottom of why this is not being ran through CircleCI.

2021-05-26 18:17 UTC, htang555 commented
Can we just have this merged manually and troubleshoot the circleCI issue later? The delay in this is due to your automation/devops whereas the actual tests run fine when done manually.

2021-05-27 11:31 UTC, ChrisHuie commented
@htang555 so the CircleCI is our end2end and integration tests on multiple browsers so usually passing unit tests is only a piece of the puzzle. Let me see if I can create a new pr that kicks off the tests

2021-05-27 11:40 UTC, ChrisHuie commented
@htang555 I tried to reopen this pr and still isn't working. Talking to CircleCI today to get this moving so we can have this in next weeks release.

2021-05-31 17:17 UTC, htang555 commented
Hey @ChrisHuie any more progress on this? This delay is really affecting us.

2021-06-01 12:14 UTC, aleksatr approved these changes

2021-06-01 15:41 UTC, ChrisHuie commented
@htang555 I managed to kick off the tests for this pr but had to essentially clone it and tie it to a pr from me. This has to do with accepting forks as prs so going into the settings as soon as I can get admin access for our CircleCI to solve this going forward. Looks like have some tests that are failing

2021-06-02 13:29 UTC, aleksatr commented
@ChrisHuie I approved the changes on the previous PR, as well as on this one, but I'm not sure why CircleCI is failing, I restarted the workflow several times, but it keeps failing.

2021-06-02 13:51 UTC, ChrisHuie commented
@aleksatr Yeah. These were the same errors I was getting when we merged it too. Later I will dig into the code and see if I can see anything that jumps out in this pr also.

2021-06-08 16:19 UTC, jmayor commented
@ChrisHuie Do you have an ETA on when our changes will be merged into master?

Looking at the circleci tests I do see this error:

DatablocksAdapter
    getUserSyncs
      ✗ Should return array of syncs
	TypeError: Object doesn't support property or method 'fromEntries'
	   at addParams (webpack:///modules/datablocksBidAdapter.js:459:7 <- test/test_index.js:49157:7)
	   at Anonymous function (webpack:///modules/datablocksBidAdapter.js:450:11 <- test/test_index.js:49147:11)
	   at Array.prototype.forEach (native code)
	   at getUserSyncs (webpack:///modules/datablocksBidAdapter.js:448:7 <- test/test_index.js:49145:7)
	   at Anonymous function (webpack:///test/spec/modules/datablocksBidAdapter_spec.js:427:7 <- test/test_index.js:219233:7)

Is this what is holding things up?  Line 459 is valid code - I am not sure why it would be failing
I can adjust the code if need be

2021-06-09 05:23 UTC, ChrisHuie commented
@jmayor yes the failing tests are currently holding this up. This pr doesn't appear to be passing the unit tests associated and also appears to be adding latency to the integration testing somewhere because it appears to be impacting other tests.

2021-06-09 16:02 UTC, jmayor commented
Ok - I re-wrote that section of the code.  It was using some ES6 code that I guess there is no polyfill for 
Lets see if it passes

2021-06-09 18:40 UTC, jmayor commented
@ChrisHuie 

Chris - looks like all the tests finally passed!

They were all related to IE11 - I guess there is no polyfill for some of the Object functions in JS

2021-06-09 20:17 UTC, patmmccann requested changes

2021-06-09 20:17 UTC, patmmccann commented on modules/datablocksBidAdapter.js
> +          var re = new RegExp('(googlebot\/|bot|Googlebot-Mobile|Googlebot-Image|Google favicon|Mediapartners-Google|bingbot|slurp|java|wget|curl|Commons-HttpClient|Python-urllib|libwww|httpunit|nutc
there is a lot of redundancy in this string; if you are looking for bot please don't also look for Googlebot, etc.

2021-06-09 20:19 UTC, patmmccann commented on test/spec/modules/datablocksBidAdapter_spec.js
> +      expect(spec.getUserSyncs({iframeEnabled: true, pixelEnabled: true}, [res_object], {gdprApplies: true, gdpr: 1, gdpr_consent: 'consent_string'}, {})).to.an('array');
to.be.an?

2021-06-09 21:20 UTC, jmayor commented on modules/datablocksBidAdapter.js
> +          var re = new RegExp('(googlebot\/|bot|Googlebot-Mobile|Googlebot-Image|Google favicon|Mediapartners-Google|bingbot|slurp|java|wget|curl|Commons-HttpClient|Python-urllib|libwww|httpunit|nutc
This is a carefully crafted list used in production - no need to change it

2021-06-09 21:24 UTC, jmayor commented on test/spec/modules/datablocksBidAdapter_spec.js
> +      expect(spec.getUserSyncs({iframeEnabled: true, pixelEnabled: true}, [res_object], {gdprApplies: true, gdpr: 1, gdpr_consent: 'consent_string'}, {})).to.an('array');
Yes - you are correct

2021-06-09 23:14 UTC, patmmccann commented on modules/datablocksBidAdapter.js
> +          var re = new RegExp('(googlebot\/|bot|Googlebot-Mobile|Googlebot-Image|Google favicon|Mediapartners-Google|bingbot|slurp|java|wget|curl|Commons-HttpClient|Python-urllib|libwww|httpunit|nutc
Yes please change it, it is wrong

2021-06-10 15:07 UTC, patmmccann requested changes

2021-06-10 15:07 UTC, patmmccann commented on modules/datablocksBidAdapter.js
> +          var re = new RegExp('(googlebot\/|bot|Googlebot-Mobile|Googlebot-Image|Google favicon|Mediapartners-Google|bingbot|slurp|java|wget|curl|Commons-HttpClient|Python-urllib|libwww|httpunit|nutc
here is proof that it is wrong, i eliminated OrangeBot from your regex and it still tested as true for 'I am a OrangeBot'

var re = new RegExp('(googlebot\/|bot|Googlebot-Mobile|Googlebot-Image|Google favicon|Mediapartners-Google|bingbot|slurp|java|wget|curl|Commons-HttpClient|Python-urllib|libwww|httpunit|nutch|phpcrawl|msnbot|jyxobot|FAST-WebCrawler|FAST Enterprise Crawler|biglotron|teoma|convera|seekbot|gigablast|exabot|ngbot|ia_archiver|GingerCrawler|webmon |httrack|webcrawler|grub.org|UsineNouvelleCrawler|antibot|netresearchserver|speedy|fluffy|bibnum.bnf|findlink|msrbot|panscient|yacybot|AISearchBot|IOI|ips-agent|tagoobot|MJ12bot|dotbot|woriobot|yanga|buzzbot|mlbot|yandexbot|purebot|Linguee Bot|Voyager|CyberPatrol|voilabot|baiduspider|citeseerxbot|spbot|twengabot|postrank|turnitinbot|scribdbot|page2rss|sitebot|linkdex|Adidxbot|blekkobot|ezooms|dotbot|Mail.RU_Bot|discobot|heritrix|findthatfile|europarchive.org|NerdByNature.Bot|sistrix crawler|ahrefsbot|Aboundex|domaincrawler|wbsearchbot|summify|ccbot|edisterbot|seznambot|ec2linkfinder|gslfbot|aihitbot|intelium_bot|facebookexternalhit|yeti|RetrevoPageAnalyzer|lb-spider|sogou|lssbot|careerbot|wotbox|wocbot|ichiro|DuckDuckBot|lssrocketcrawler|drupact|webcompanycrawler|acoonbot|openindexspider|gnam gnam spider|web-archive-net.com.bot|backlinkcrawler|coccoc|integromedb|content crawler spider|toplistbot|seokicks-robot|it2media-domain-crawler|ip-web-crawler.com|siteexplorer.info|elisabot|proximic|changedetection|blexbot|arabot|WeSEE:Search|niki-bot|CrystalSemanticsBot|rogerbot|360Spider|psbot|InterfaxScanBot|Lipperhey SEO Service|CC Metadata Scaper|g00g1e.net|GrapeshotCrawler|urlappendbot|brainobot|fr-crawler|binlar|SimpleCrawler|Livelapbot|Twitterbot|cXensebot|smtbot|bnf.fr_bot|A6-Indexer|ADmantX|Facebot|Twitterbot|OrangeBot|memorybot|AdvBot|MegaIndex|SemanticScholarBot|ltx71|nerdybot|xovibot|BUbiNG|Qwantify|archive.org_bot|Applebot|TweetmemeBot|crawler4j|findxbot|SemrushBot|yoozBot|lipperhey|y!j-asr|Domain Re-Animator Bot|AddThis)', 'i');
 

undefined
re.test('I am a bot')
true
re.test('I am a dog')
false
re.test('I am a OrangeBot')
true
var re2 = new RegExp('(googlebot\/|bot|Googlebot-Mobile|Googlebot-Image|Google favicon|Mediapartners-Google|bingbot|slurp|java|wget|curl|Commons-HttpClient|Python-urllib|libwww|httpunit|nutch|phpcrawl|msnbot|jyxobot|FAST-WebCrawler|FAST Enterprise Crawler|biglotron|teoma|convera|seekbot|gigablast|exabot|ngbot|ia_archiver|GingerCrawler|webmon |httrack|webcrawler|grub.org|UsineNouvelleCrawler|antibot|netresearchserver|speedy|fluffy|bibnum.bnf|findlink|msrbot|panscient|yacybot|AISearchBot|IOI|ips-agent|tagoobot|MJ12bot|dotbot|woriobot|yanga|buzzbot|mlbot|yandexbot|purebot|Linguee Bot|Voyager|CyberPatrol|voilabot|baiduspider|citeseerxbot|spbot|twengabot|postrank|turnitinbot|scribdbot|page2rss|sitebot|linkdex|Adidxbot|blekkobot|ezooms|dotbot|Mail.RU_Bot|discobot|heritrix|findthatfile|europarchive.org|NerdByNature.Bot|sistrix crawler|ahrefsbot|Aboundex|domaincrawler|wbsearchbot|summify|ccbot|edisterbot|seznambot|ec2linkfinder|gslfbot|aihitbot|intelium_bot|facebookexternalhit|yeti|RetrevoPageAnalyzer|lb-spider|sogou|lssbot|careerbot|wotbox|wocbot|ichiro|DuckDuckBot|lssrocketcrawler|drupact|webcompanycrawler|acoonbot|openindexspider|gnam gnam spider|web-archive-net.com.bot|backlinkcrawler|coccoc|integromedb|content crawler spider|toplistbot|seokicks-robot|it2media-domain-crawler|ip-web-crawler.com|siteexplorer.info|elisabot|proximic|changedetection|blexbot|arabot|WeSEE:Search|niki-bot|CrystalSemanticsBot|rogerbot|360Spider|psbot|InterfaxScanBot|Lipperhey SEO Service|CC Metadata Scaper|g00g1e.net|GrapeshotCrawler|urlappendbot|brainobot|fr-crawler|binlar|SimpleCrawler|Livelapbot|Twitterbot|cXensebot|smtbot|bnf.fr_bot|A6-Indexer|ADmantX|Facebot|Twitterbot|memorybot|AdvBot|MegaIndex|SemanticScholarBot|ltx71|nerdybot|xovibot|BUbiNG|Qwantify|archive.org_bot|Applebot|TweetmemeBot|crawler4j|findxbot|SemrushBot|yoozBot|lipperhey|y!j-asr|Domain Re-Animator Bot|AddThis)', 'i');
undefined
re2.test('I am a OrangeBot')
true

2021-06-10 15:53 UTC, jmayor commented on modules/datablocksBidAdapter.js
> +          var re = new RegExp('(googlebot\/|bot|Googlebot-Mobile|Googlebot-Image|Google favicon|Mediapartners-Google|bingbot|slurp|java|wget|curl|Commons-HttpClient|Python-urllib|libwww|httpunit|nutc
@patmmccann 
I am not saying that you are wrong - I am just a bit frustrated that we are almost a month into the process.  Aside from saving bits going across the wire - your suggestions would not change the output of the function

To reduce the code base - I am just going to remove this check since it does not need to be in the client side to begin with.  The useragent is being parsed and filtered on the server side anyway.

I'll push up a change later today

2021-06-10 20:33 UTC, patmmccann commented on modules/datablocksBidAdapter.js
> +          var re = new RegExp('(googlebot\/|bot|Googlebot-Mobile|Googlebot-Image|Google favicon|Mediapartners-Google|bingbot|slurp|java|wget|curl|Commons-HttpClient|Python-urllib|libwww|httpunit|nutc
It is no one's job but your own to push code that checks out; your last commit was one day ago and you still don't have circleci running because you haven't unfollowed your own fork. I would say we are still zero days into the process bc you haven't submitted functioning code yet. It is not the reviewer's job to fix your code and your devops. You are coming across as quite demanding and entitled.

2021-06-11 06:14 UTC, ChrisHuie commented
Looks like we are getting closer! The datablocks errors seem to be cleared up but still looks like we are getting errors in a couple other adapters which I am assuming has to deal with storage manager interaction or sinon itself.

2021-06-11 20:00 UTC, htang555 commented
Thanks @ChrisHuie and @patmmccann for your guidance. Are the additional CircleCI failures anything we can handle on our end or do you guys have a handle on it?

2021-06-15 16:25 UTC, jmayor commented on modules/datablocksBidAdapter.js
> +          var re = new RegExp('(googlebot\/|bot|Googlebot-Mobile|Googlebot-Image|Google favicon|Mediapartners-Google|bingbot|slurp|java|wget|curl|Commons-HttpClient|Python-urllib|libwww|httpunit|nutc
@patmmccann 
I have no interest in arguing with you and I apologize if I came off as demanding - I think you misunderstood my language as it was not my intention. There were issues with CircleCI at the beginning of the PR that were outside of our control.  @ChrisHuie helped us resolve
  
The only thing holding this up now is your change request - which we resolved on our end by removing the regex.  Please approve the change request so that we can move on

2021-06-15 21:47 UTC, patmmccann commented on modules/datablocksBidAdapter.js
> +          var re = new RegExp('(googlebot\/|bot|Googlebot-Mobile|Googlebot-Image|Google favicon|Mediapartners-Google|bingbot|slurp|java|wget|curl|Commons-HttpClient|Python-urllib|libwww|httpunit|nutc
Thank you,  your change lgtm

2021-06-15 21:47 UTC, patmmccann approved these changes

2021-06-16 12:05 UTC, ChrisHuie approved these changes

2021-06-16 12:08 UTC, ChrisHuie commented
@htang555 and @jmayor this looks to be good to go now. Thanks for working with us to get this pr passing :) Merging it now

2021-06-16 12:33 UTC, merged