[criteo] Updated adapter to use mediaTypes.video instead of custom parameters
prebid/Prebid.js pull request #6778
Opened 2021-05-18 07:08 UTC by leonardlabat

## Type of change
- [X] Feature

## Description of change
Updated adapter to use mediaTypes.video instead of custom parameters.
Reading from custom parameters is kep for now to ensure backward compatibility. Documentation will be updated once PBJS 5.0 will be released.

2021-05-18 15:59 UTC, patmmccann commented on modules/criteoBidAdapter.js
> +          skip: bidRequest.mediaTypes.video.skippable || bidRequest.params.video.skip,
openrtb = skip

2021-05-18 16:00 UTC, patmmccann requested changes
OpenRTB parameter is skip, feel free to support skippable as well

https://github.com/prebid/Prebid.js/issues/5237

2021-05-19 06:47 UTC, leonardlabat commented on modules/criteoBidAdapter.js
> +          skip: bidRequest.mediaTypes.video.skippable || bidRequest.params.video.skip,
Thanks @patmmccann , fixed

2021-05-19 16:23 UTC, patmmccann approved these changes

2021-05-19 19:58 UTC, merged

2021-06-02 18:25 UTC, gglas commented
hey @leonardlabat wanted to follow up here - will you be able to add the adomain stub in the next week?

2021-06-02 19:19 UTC, patmmccann commented
it got merged already https://github.com/prebid/Prebid.js/pull/6915

2021-06-02 19:26 UTC, leonardlabat commented
Yep exactly
Thanks @patmmccann for the quick answer

2021-06-02 19:59 UTC, gglas commented
perfect thank you both