Feature: Limit send all bid keys
prebid/Prebid.js pull request #6822
Opened 2021-05-24 17:39 UTC by r-schweitzer

## Type of change
Feature

## Description of change
Allows a publisher to limit the number 'sendAllBids' keys sent to the adServer. For example hb_bidder_rubicon is one of the more redudant keys we would like to stop sending but we still need hb_bidder key sent. This would similar to the targetingControl option, allowTargetingKeys.

Sample Config:
Example will not send hb_bidder_runicon
`      
    enableSendAllBids: true,
    targetingControls: {
        allowTargetingKeys: ['BIDDER', 'AD_ID', 'PRICE_BUCKET'],
        allowSendAllBidsTargetingKeys: ['PRICE_BUCKET', 'AD_ID']
    }
`

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
Coming soon

2021-05-24 23:37 UTC, patmmccann commented on src/targeting.js
> +            allowedSendAllBidTargeting.includes(key))
you can't use includes in ie11

2021-05-24 23:38 UTC, patmmccann requested changes

2021-05-24 23:38 UTC, patmmccann commented on src/targeting.js
> +            allowedSendAllBidTargeting.includes(key))
import includes from 'core-js-pure/features/array/includes.js';

is the polyfill syntax

2021-05-25 11:55 UTC, patmmccann approved these changes

2021-06-08 16:42 UTC, ChrisHuie approved these changes

2021-06-08 20:29 UTC, merged