PBS Bid Adapter: Fix duplicate imp.id
prebid/Prebid.js pull request #6933
Opened 2021-06-03 19:31 UTC by FilipStamenkovic

## Type of change

- [x] Bugfix

## Description of change

This PR suggests deduplication of `imp.id` by adding suffix `-2` to the `imp.id`, if duplication is detected.  
Change `bidIdMap` so that the keys are in format `imp.id-bidder` instead of `adUnit.code-bidder`.
## Other information

Fixes #6910

2021-06-03 21:18 UTC, hnkhandev requested changes
Since this is not limited to just two sets of identical adunits (e.g adding native could make it three sets), I would recommend using a map/obj to keep track of the imp ids. With the current proposed changes, it would label triple adUnits as '-2-3' instead of '-2'.

`
let impIds = [];
...
...
...
let id = adUnit.code;
if (!(id in impIds)) {
   impIds[id] = 1
} else {
   impIds[id]++
   id = `${id}-${impIds[id]}`;
}  
`

2021-06-03 21:31 UTC, FilipStamenkovic commented
@hnkhandev Thanks for the review, it should be fixed now. I overlooked how my `while` loop would behave for 'triplets'.

2021-06-03 22:07 UTC, hnkhandev approved these changes
Looks good. I can't spot any further issues.

2021-06-04 17:10 UTC, ChrisHuie approved these changes

2021-06-04 17:11 UTC, merged