Buzzoola Bid Adapter: add advertiser domain and native media type support
prebid/Prebid.js pull request #6956
Opened 2021-06-07 09:19 UTC by Sonic0588

## Type of change

- [x] Bugfix
- [x] Feature

## Description of change

- add advertiser adomain support
- add native media type support

2021-06-07 10:31 UTC, patmmccann approved these changes

2021-06-07 10:33 UTC, patmmccann requested changes
Please note Unexpected EOF in ci tests

2021-06-07 13:51 UTC, ChrisHuie approved these changes

2021-06-07 13:52 UTC, merged

2021-06-10 18:21 UTC, jeanstemp commented
https://github.com/prebid/prebid.github.io/pull/3011