Rule Enforcement: include support for adomain
prebid/Prebid.js pull request #6986
Opened 2021-06-09 15:13 UTC by ChrisHuie

2021-06-09 19:26 UTC, patmmccann requested changes
please restore widespace

2021-06-09 19:58 UTC, patmmccann requested changes

2021-06-09 19:58 UTC, patmmccann commented on modules/widespaceBidAdapter.js
> +        'hb.floor': bid.bidfloor || '',
i think you got the old widespace.js

2021-06-09 23:22 UTC, patmmccann approved these changes

2021-06-10 01:39 UTC, gglas approved these changes
lgtm

2021-06-10 01:48 UTC, merged