Adding amxIdSystem
prebid/Prebid.js pull request #6996
Opened 2021-06-09 22:27 UTC by nickjacob

## Type of change

- [x ] Other

## Description of change

Adding the `amxIdSystem` userId submodule. This provides an `amxId` user ID and eid.

contact email of the adapter’s maintainer: prebid@amxrtb.com
- [ x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

PR in docs repo: https://github.com/prebid/prebid.github.io/pull/3026

2021-06-10 15:46 UTC, smenzer commented
@nickjacob can you please also add test to `userId_spec.js` - you can follow the same updates as other modules

2021-06-10 19:11 UTC, nickjacob commented
@smenzer thanks for pointing that out -- looks like when 5.0 got merged into master it caused some weird issues in userId_spec.js -- I tried to resolve it in a way that made sense (specifically here -- in master: https://github.com/prebid/Prebid.js/blob/master/test/spec/modules/userId_spec.js#L532)

2021-06-10 22:06 UTC, nickjacob commented
thanks @patmmccann  -- added to submodules.json

2021-06-11 14:51 UTC, smenzer requested changes

2021-06-11 14:51 UTC, smenzer commented on modules/amxIdSystem.js
> +        params
when i add run your code on page (I'd recommend adding it to `userId_example.html` under integration examples), i get an error with the response from the server. i believe `params` should be `JSON.stringify(parms)` here as it shows as `[object Object]` in the network call. either that, or the server is not responding properly.

2021-06-11 15:22 UTC, nickjacob commented
Thanks @smenzer -- sorry about that! I added the integration example & fixed that request.

I also removed the "timeout" option

2021-06-14 08:19 UTC, smenzer requested changes
just need to fix `expires` and then this looks good to me

2021-06-14 08:19 UTC, smenzer commented on modules/amxIdSystem.md
> +| expires               | Optional | Number <= 30 | number of days until the stored ID expires. **Must be less than or equal to 30** | `30`      |
this is not an optional parameter if you are using the built-in storage

2021-06-14 08:19 UTC, smenzer commented on integrationExamples/gpt/userId_example.html
> +                "name": "amxId"
you must pass in `expires`

2021-06-14 16:08 UTC, smenzer approved these changes
LGTM

2021-06-14 16:30 UTC, merged