WIdespace adapter update for prebid 5
prebid/Prebid.js pull request #7006
Opened 2021-06-10 16:43 UTC by talha08

## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Widespace adapter: add support for adomain and floors module for Prebid 5.
#6465
#6650

2021-06-10 18:50 UTC, patmmccann commented
tyvm!

2021-06-10 20:31 UTC, talha08 commented
I can see some test cases failed in other adapters.  But here it shows, **Your tests failed on CircleCI**

I'm new here, What should I need to do? Please let me know!
@patmmccann

2021-06-22 08:41 UTC, Fawke requested changes
Hi @talha08,

Thanks for this PR. Change looks good but I had a few things which can be looked at. 
1. I don't see any unit test case covering the new `getBidFloor` function that you wrote.
2. You need to submit a docs PR to change this field, `Floors Module Support` to `yes`.

Do not worry about the test cases for other adapters failing on cirle ci, I see that they're passing now. Some tests are flaky which can cause the circle ci build to fail.

2021-06-22 08:41 UTC, Fawke commented on modules/widespaceBidAdapter.js
> +  });
This can be wrapped in a try/catch block incase getFloor throws an error.

2021-07-07 05:39 UTC, Fawke commented
@talha08 Hey, just checking! I see no updates on this PR for quite a few days, do you need any help with this?

2021-09-15 08:07 UTC, Fawke commented
@ChrisHuie Do we wanna close this PR, I haven't seen any activity on this since two months.

2021-09-29 14:52 UTC, ChrisHuie commented
@Fawke I will just change the assignee to me so you don't have to worry about it :) I will try and reach out.

2021-11-15 12:25 UTC, ChrisHuie commented
@talha08 is this pr still being worked on? Haven't heard anything in a while and we are cleaning out stale prs. If I don't hear back by Thanksgiving I will just go ahead and close this out and you can reopen again later if needed.

2021-11-23 21:59 UTC, closed without merging