No bid version 1.3.1
prebid/Prebid.js pull request #7177
Opened 2021-07-14 00:10 UTC by redaguermas

## Type of change
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Added support for alias "duration".

- test parameters for validating bids
```
{
  bidder: 'duration',
  params: {
    // ...
  }
}
```

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:
- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/pull/3102

2021-07-14 00:24 UTC, redaguermas commented
Hello,
Can you please review this PR. The error in the CircleCI is unrelated to my code.

2021-07-14 07:30 UTC, ChrisHuie commented
@redaguermas rerean tests and passed but looks like you uploaded several of your ide files with this pr and your package-lock file. Can you please remove all those files and add a test case for the nobid change.

2021-07-14 16:36 UTC, robertrmartinez commented
@redaguermas Yeah please remove all of your extra files.

Should just be only two files, the bid adapter, and the associated _spec file testing the change.

package-lock should not be in there either.

2021-07-15 16:05 UTC, bretg requested changes
please also remove nobidBidAdapter.js.orig and the changes to package-lock.json

2021-07-15 16:05 UTC, bretg commented on modules/nobidBidAdapter.js
> +    { code: 'duration', gvlib: 674 }
this should be gvlid,not glvlib

2021-07-15 16:05 UTC, bretg commented on a
> +[16:58:25] Using gulpfile ~/Documents/work/nobid/Prebid.js/gulpfile.js
this file is a mistake. please delete it

2021-07-19 18:40 UTC, redaguermas commented
Hello @bretg ,
Thank you for the feedback. Can you please review the latest changes.
-Regards

2021-07-20 17:50 UTC, ChrisHuie approved these changes

2021-07-20 17:52 UTC, merged