Change for version 5.0, advertisersDomains property is added
prebid/Prebid.js pull request #7203
Opened 2021-07-21 15:47 UTC by cs83

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2021-07-21 20:08 UTC, patmmccann approved these changes

2021-07-21 20:09 UTC, patmmccann requested changes
I think you just need to change to .deep.equal

2021-07-21 20:09 UTC, patmmccann commented on test/spec/modules/smarticoBidAdapter_spec.js
> +	  expect(result[0].meta).to.equal(expectedResponse[0].meta)
deep.equal

2021-07-22 12:49 UTC, ChrisHuie approved these changes

2021-07-22 12:49 UTC, merged