Halo ID url params, RTD dupe protection, doc update
prebid/Prebid.js pull request #7204
Opened 2021-07-22 03:21 UTC by anthonylauzon

## Type of change
- [X] Bugfix

This is a small update to the Halo code.  It adds configurable URL parameters to the ID module, adds array-level data duplication protection to the RTD module, and updates the RTD documentation.

- contact email of the adapter’s maintainer
prebid@audigent.com

## Other information
https://github.com/prebid/Prebid.js/pull/7060
https://github.com/prebid/Prebid.js/pull/6505

2021-07-25 21:40 UTC, anthonylauzon commented
@ChrisHuie this is similar to the last one, a few minor changes to the id & rtd system

2021-07-27 14:25 UTC, smenzer requested changes
can you please also submit a prebid docs PR for the new `url` config param?

2021-07-27 14:25 UTC, smenzer commented on modules/haloIdSystem.js
> +      config.params.urlArg);
this parameter isn't documented in your .md file...should it be? what do you expect here?

2021-07-28 00:53 UTC, anthonylauzon commented
@smenzer update docs for url arg and there is a pr for the website here: https://github.com/prebid/prebid.github.io/pull/3154

2021-07-28 08:56 UTC, smenzer approved these changes
LGTM

2021-07-28 08:56 UTC, merged

2021-07-28 18:15 UTC, MartianTribe commented
https://github.com/prebid/prebid.github.io/pull/3154