TheMediaGrid: fill user.id from fpd cookie
prebid/Prebid.js pull request #7279
Opened 2021-08-09 16:48 UTC by TheMediaGrid

## Type of change

- [x] Feature

## Description of change

Check fpd cookie and send it in ad request if available

- grid-tech@themediagrid.com
- [x] official adapter submission

2021-08-09 17:23 UTC, patmmccann commented
this appears to largely duplicate the pubcid and I believe should not be allowed.

2021-08-09 19:02 UTC, patmmccann commented
@TheMediaGrid I opened issue https://github.com/prebid/Prebid.js/issues/7280 to discuss if this functionality is allowed.

2021-08-18 16:45 UTC, patmmccann commented
Hi @TheMediaGrid ; we discussed this at length in the js committee today: Can you make sure all this behavior is opt-in by a publisher?

 Also, we plan to make it so publishers can prevent adapters from using the storage.setCookie method in the future, but that functionality is not yet available.

2021-08-18 16:46 UTC, patmmccann requested changes

2021-08-18 16:46 UTC, patmmccann commented on modules/gridBidAdapter.js
> +function makeNewUserIdInFPDCookie() {
please make this dependent on adapter config that defaults to 'off'

2021-08-30 20:56 UTC, patmmccann commented
Hello @TheMediaGrid 

Any feedback on the requested changes?

2021-08-31 21:21 UTC, TheMediaGrid commented
Hello! We have added bidder config option 'cookieSettingAllowed' to control cookies adding

2021-09-01 16:00 UTC, patmmccann commented on modules/gridBidAdapter.js
> +    storage.setCookie(USER_ID_KEY, value, expires);
why not use local storage?

2021-09-01 16:00 UTC, patmmccann commented on modules/gridBidAdapter.js
> +  return storage.getCookie(USER_ID_KEY) || makeNewUserIdInFPDCookie();
why not use local storage?

2021-09-01 16:07 UTC, patmmccann commented on modules/gridBidAdapter.js
> +    storage.setCookie(USER_ID_KEY, value, expires);
Expanding on this: cookies get appended to all requests that a browser makes to the publisher in the http headers, and can lead to overflows of CDN limits and failed requests. Eg cloudflare has a 4k limit. Publishers that make tons of requests to the same domain may see actual bandwidth consumed noticibly change. Local storage does not have this disadvantage.

2021-09-02 15:00 UTC, TheMediaGrid commented
Hello! Now we use localStorage instead Cookies

2021-09-06 13:56 UTC, TheMediaGrid commented
@patmmccann Hello, is this ready to merge, or there is some additional questions?

2021-09-07 15:03 UTC, patmmccann commented
> @patmmccann Hello, is this ready to merge, or there is some additional questions?

Please add a docs pr, code lgtm

2021-09-08 09:09 UTC, TheMediaGrid commented
Pull request in the doc repo - https://github.com/prebid/prebid.github.io/pull/3254

2021-09-08 14:53 UTC, patmmccann approved these changes

2021-09-08 14:54 UTC, patmmccann commented
Merging, but please note my change request on the docs PR as well as please rebase to master your other two pr's on your adapter to these changes don't show. Thanks!

2021-09-08 14:55 UTC, merged