TrustX Bid Adapter: Use new format as default + new format for keywords
prebid/Prebid.js pull request #7288
Opened 2021-08-11 17:14 UTC by PWyrembak

## Type of change

- [x] Feature

## Description of change

Use new format as default + new format for keywords

- paul@trustx.org
- [x] official adapter submission

2021-08-17 12:00 UTC, TheMediaGrid commented
hey team, any chance we could get this one reviewed? @msm0504 
we really need this one to be deployed this week

2021-08-19 21:15 UTC, ChrisHuie commented
@TheMediaGrid this is a pretty large pr and rewrite so could take a bit to go through.

2021-08-23 12:07 UTC, Fawke commented on modules/trustxBidAdapter.js
> +function reformatKeywords(pageKeywords) {
I see that a bunch of validations is done on the ortb2/fpd object here. Just wanted to let you know that a prebid.js optional modlue [validationFpdModule](https://docs.prebid.org/dev-docs/modules/validationFpdModule.html) was released recently. You may still need this if it's not included in the build.

Do you need to reformat them?

2021-08-23 12:12 UTC, Fawke requested changes
Hi @piwanczak,

Changes mostly look good. For testing, I wanted to receive a test bid response from your endpoint, but none of the examples currently given in the md file works. Can you please update them (both video and banner). Also, if you can update the examples to include the required `mediaTypes` property, that'll be great.

Apart from that, please check the inline comment.

2021-08-23 21:15 UTC, PWyrembak commented
Hello! We have fixed the md file. As for the validation of keywords, you probably misunderstood, we validate mostly keywords from the adUnit parameters

2021-08-24 09:20 UTC, Fawke approved these changes
LGTM

2021-08-24 09:21 UTC, merged