Conversant: add new Publink user id module
prebid/Prebid.js pull request #7322
Opened 2021-08-19 15:53 UTC by johnwier

## Type of change
- [X ] Feature

## Description of change
pbjs.setConfig({
userSync: {
userIds: [{
name: "publinkId",
storage: {
name: "pbjs_publink",
type: "cookie",
expires: 30
},
params: {
e: "e80b5017098950fc58aad83c8c14978e", // example hashed email (md5)
}
}],
auctionDelay: 50 // 50ms maximum auction delay, applies to all userId modules
}
});

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
Link to documentation PR 
https://github.com/prebid/prebid.github.io/pull/3219
## Other information

2021-08-23 18:52 UTC, patmmccann commented
How is this different from the publisher provided id module?

2021-08-23 21:50 UTC, johnwier commented
We wanted this to be self contained so this is the only thing the publishers need and not have to load additional scripts

2021-08-24 18:55 UTC, patmmccann commented
This is a module to pass hashed email, we already have a module to pass hashed email; I think I'm missing something

2021-08-25 11:02 UTC, FilipStamenkovic requested changes
Code looks fine.  
Take a look at my other comments.  
Also, include your submodule in `.submodules.json` list.

2021-08-25 11:02 UTC, FilipStamenkovic commented on modules/publinkIdSystem.js
> + * @module modules/conversantIdSystem
`conversantIdSystem` could be confusing, maybe you should rename it to `publinkIdSystem`.

2021-08-25 16:09 UTC, patmmccann commented
Hi @johnwier 

As your config requires a hashed id, a pub will still have to write script to populate it. Is there any additional functionality this module provides that is not in existing modules? If not, I think it makes more sense for adapters to pull from existing modules rather than provide competing functionality that is identical.

2021-09-01 17:24 UTC, johnwier commented
I've finished the recent updates so there's no need to hold off now

2021-09-03 10:03 UTC, FilipStamenkovic approved these changes
Code looks good to me.  
@patmmccann what do you think?

2021-09-07 21:33 UTC, patmmccann commented on modules/userId/eids.js
> +    source: 'epsilon.com',
this seems incorrect; how is epsilon a source, they appear to be a consumer of the id

2021-09-08 16:25 UTC, patmmccann commented
my only remaining question is on the source in the eids object. It seems the publisher domain should be the source? Or perhaps match to pubcid.org? I am confused on the epsilon branding.

2021-09-08 19:37 UTC, johnwier commented
since conversant is owned by epsilon there is an ongoing effort to make the branding more consistent

2021-09-08 19:45 UTC, patmmccann commented
how is this related to conversant other than you authored the PR?

2021-09-08 19:47 UTC, patmmccann commented
to put this another way, if this is simply an id module to put email hashes in bid requests, why would conversant or epsilon be the source of the information?

2021-09-08 19:50 UTC, patmmccann commented
Perhaps I am missing something here, is the workflow the publisher hashes the email, hits the conversant endpoint and they end back a rehash? If so, than perhaps the rehash makes sense as having epsilon as the source.

2021-09-08 19:52 UTC, merged

2021-09-08 20:00 UTC, pycnvr commented
@patmmccann Yes, that's correct.  It's an encrypted guid so conversant/epsilon is the issuer.  Thanks again for the help!
@FilipStamenkovic Thanks for the reviews, too.

2021-09-14 18:49 UTC, jdwieland8282 commented
@pycnvr are you still up for walking the Prebid Identity PMC through you new module tomorrow?  I'm personally curious to learn more about how you get the users email into `params.e`

2021-09-14 19:46 UTC, pycnvr commented
@jdwieland8282 Sure.  The flow is straightforward.  It would require a bit of custom codes from the publisher to call pbjs.setConfig one more time when the hash is available, followed up by a call to pbjs.refreshUserIds to crank the wheel.  That's why it'd be much nicer if we can integrate with the import lib somehow.

2021-09-14 20:21 UTC, jdwieland8282 commented
Right I sort of thought that's the direction we wanted to go, Publink could grab the hashed email from the import lib.  We should at a min support that for pubs who don't want to write custom code to add a hashed email to `params.e`. 

Second question, for pubs who want to populate `params.e` on their own, how do we ensure that the value is hashed?

2021-09-14 22:18 UTC, pycnvr commented
@jdwieland8282 That being a config parameter, it'd be up to PubLink and other similar modules to do a validation.  A regex for hex would be sufficient.  Much easier than email address scans.  What do you think?

2021-09-15 15:52 UTC, jdwieland8282 commented
@pycnvr  agreed.  

More broadly, I think we are at a crossroads here and this module is a good forcing mechanism for us to discuss it.  That crossroads is "does the Prebid community want to have an official position on passing clear text emails, hashed emails, or no emails", and really it's a debate between the first 2 at this point.

2021-09-16 12:38 UTC, patmmccann commented
@pycnvr it seems this pr skips some circleci tests for reasons I cannot determine. Most other recent PRs are doing the same and we are ttrying to fix. However, this is what happens when all tests run https://app.circleci.com/pipelines/github/prebid/Prebid.js/8055/workflows/0e2d84af-44e7-4586-b5f3-c6f810c101c0/jobs/17925 or https://app.circleci.com/pipelines/github/prebid/Prebid.js/8067/workflows/7312b412-4840-4c0e-b3a6-79bd9994a203/jobs/17937

You can see on IE, the :443 protocol is added to the url and the test fails. Can you look into this by any chance? 

Thanks!

2021-09-16 14:41 UTC, pycnvr commented
@patmmccann Yes I'll take a look.  Thanks!