TheMediaGrid: Request key fixes
prebid/Prebid.js pull request #7385
Opened 2021-09-07 07:31 UTC by TheMediaGrid

## Type of change

- [x] Refactoring (no functional changes, no api changes)

## Description of change

All id like request fields converted to string

- grid-tech@themediagrid.com
- [x] official adapter submission

2021-09-07 15:34 UTC, patmmccann approved these changes

2021-09-07 15:35 UTC, patmmccann requested changes
This includes #7279 

Can you keep them different?

2021-09-08 15:07 UTC, patmmccann approved these changes

2021-09-08 15:07 UTC, patmmccann commented
Please just resolve conflicts

2021-09-08 16:31 UTC, TheMediaGrid commented
Done, conflicts resolved

2021-09-08 16:34 UTC, merged