freewheel-ssp add schain in request params
prebid/Prebid.js pull request #7504
Opened 2021-09-28 01:57 UTC by xwang202

## Type of change
- [x] Feature

## Description of change
add schain in request params

2021-09-28 15:20 UTC, ChrisHuie commented
@xwang202 schain seems to be causing a linting error in the way it is passed in the test file

2021-09-28 20:48 UTC, patmmccann requested changes

2021-11-03 07:59 UTC, xwang202 commented on test/spec/modules/freewheel-sspBidAdapter_spec.js
> +      const bidRequests = spec.buildRequests(bid);
Hi @patmmccann ,  I updated again. Please check. Thanks.

2021-11-10 08:16 UTC, xwang202 commented on test/spec/modules/freewheel-sspBidAdapter_spec.js
> +      const bidRequests = spec.buildRequests(bid);
@patmmccann The test has been updated. I think the new error are not caused by our test. Please double check. Thanks.

2021-11-18 17:11 UTC, patmmccann approved these changes

2021-11-18 17:11 UTC, patmmccann commented
LGTM

2021-11-18 17:12 UTC, merged