VidoomyBidAdapter: refactor cookie sync
prebid/Prebid.js pull request #7601
Opened 2021-10-19 14:41 UTC by sasanfarokh

## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Just call cookie sync urls sequentially with a 500ms delay between them.

2021-10-31 08:04 UTC, sasanfarokh commented
> While testing your bidder I found some small errors. You can see them in separate comments. From Prebid perspective, you don't have to fix those issues. But, I strongly suggest that you fix them anyway, it will make your adapter run a bit faster.
> 
> Also, why are you passing `ua` (userAgent string) in query params, you already have that information in HTTP header?

Hey, About the user-agent you're right, It's already exists in HTTP headers, but currently our backend apps may read it from querystring, I want to leave it as before.

2021-11-01 08:46 UTC, FilipStamenkovic requested changes
Your tests are failing, please take a look at CircleCI output.

2021-11-02 08:49 UTC, FilipStamenkovic requested changes

2021-11-02 08:49 UTC, FilipStamenkovic commented on modules/vidoomyBidAdapter.js
> +function getUserSyncs (syncOptions, responses, gdprConsent, uspConsent) {
You are not using `uspConsent` anywhere.  

You must include `uspConsent` string in your cookie sync urls.

2021-11-02 12:12 UTC, FilipStamenkovic approved these changes

2021-11-02 12:13 UTC, merged