adxcgBidAdapter: updated backend protocol
prebid/Prebid.js pull request #7750
Opened 2021-11-23 21:09 UTC by adxcgcom

## Type of change
- [X] Feature

## Description of change
 Change of backend integration protocol from internal to official openrtb 2.5

- test parameters for validating bids
```
{
 var adUnits = [{
                    code: 'banner-ad-div',
                    mediaTypes: {
                        banner: {
                            sizes: [
                                [300, 250],
                                [300, 600]
                            ]
                        }
                    },
                    bids: [{
                        bidder: 'adxcg',
                        params: {
                            adzoneid: '1'
                        }
                    }]
                }, {
                    code: 'native-ad-div',
                    mediaTypes: {
                        native: {
                             image: {
                                sendId: false,
                                required: false,
                                sizes: [127, 83]
                            },
                            icon: {
                                sizes: [80, 80],
                                required: false,
                                sendId: true,
                            },
                            title: {
                                sendId: false,
                                required: false,
                                len: 75
                            },
                            body: {
                                sendId: false,
                                required: false,
                                len: 200
                            },
                            cta: {
                                sendId: false,
                                required: false,
                                len: 75
                            },
                            sponsoredBy: {
                                sendId: false,
                                required: false
                            }
                        }
                    },
                    bids: [{
                            bidder: 'adxcg',
                            params: {
                                adzoneid: '2379'
                            }                        
                    }]
            },
            {
                code: 'video-div',
                mediaTypes: {
                    video: {
                            playerSize: [640, 480],
                            context: 'instream',
                            mimes: ['video/mp4'],
                            protocols: [2, 3, 5, 6, 8],
                            playback_method: ['auto_play_sound_off'],
			                maxduration: 100,
                            skip: 1
                        }
                },
                bids: [{
                    bidder: 'adxcg',
                    params: {
                        adzoneid: '20'                       
                    }a
                }]
            }
        ];
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer   info@adxcg.com
- [X] official adapter submission

2021-11-29 10:18 UTC, Fawke commented on modules/adxcgBidAdapter.js
> +      ajax(replaceAuctionPrice(bid.nurl, bid.originalCpm))
I'm not sure if a bid adapter is allowed to make an Ajax request apart from an Auction request. Is there any way you can avoid it?

2021-11-29 10:22 UTC, Fawke requested changes
@adxcgcom Hi, this looks good, just a small observation on the ajax request that I saw on the `onBidWon` hook. I'm not sure if this is allowed.

Apart from that, I see that this adapter doesn't have a Gvlid yet. If you have a Gvlid and if you think that'll help, I'd advise to add that.

2021-11-29 12:01 UTC, adxcgcom commented
Fawke, thx for review. We updated from ajax to triggerPixel, as this is most commonly used in bidAdapters.  GvlID is ok as is.

2021-12-01 08:18 UTC, Fawke approved these changes
LGTM

2021-12-01 08:18 UTC, merged