ozone 2.7.0 adapter updates
prebid/Prebid.js pull request #7856
Opened 2021-12-13 16:53 UTC by afsheenb

## Type of change
- [X] Feature

## Description of change
- Added support for client side sChain module

- PR for updated documentation can be found at https://github.com/prebid/prebid.github.io/pull/3461

engineering@ozoneproject.com

2021-12-13 17:18 UTC, afsheenb commented
The circleCI error for the build of this PR is unrelated to our adapter:

```
1) builds and sends data
     finteza analytics adapter track bid response
     AssertionError: expected 'POST' to equal 'GET'
    at Context.<anonymous> (webpack:///test/spec/modules/fintezaAnalyticsAdapter_spec.js:122:46 <- test/test_index.js:322190:143
```

2021-12-13 17:43 UTC, patmmccann commented
Can you fix your longstanding lgtm alert in this pr?

2021-12-13 17:48 UTC, patmmccann reviewed
plz fix https://lgtm.com/projects/g/prebid/Prebid.js/snapshot/c6ded29e3bcadcc3ec5ebc3cefb85400271d95cd/files/modules/ozoneBidAdapter.js?sort=name&dir=ASC&mode=heatmap#x225042b871758e91:1 line 603, useless assignment

2021-12-14 17:35 UTC, afsheenb commented
Done @patmmccann, fix submitted for the unused assignment.

2021-12-14 17:53 UTC, afsheenb commented
Again, the circleCI error is unrelated to our adapter changes:

```
1) should do nothing when bid metadata is not set
     FeedAdAdapter event tracking calls onTimeout handler
     AssertionError: expected 1 to equal 0
    at Context.<anonymous> (webpack:///test/spec/modules/feedadBidAdapter_spec.js:445:45 <- test/test_index.js:321704:142)
```

2021-12-14 19:32 UTC, patmmccann commented on modules/ozoneBidAdapter.js
> +        logInfo('added fdp.site');
typo

2021-12-14 19:33 UTC, patmmccann commented
LGTM ; just one typo to fix plz

2021-12-15 16:11 UTC, patmmccann approved these changes

2021-12-15 16:13 UTC, patmmccann requested changes
new linting error to fix, then appears good to go

2021-12-15 16:13 UTC, patmmccann commented on modules/ozoneBidAdapter.js
> +
this is making a linting error

2021-12-16 16:21 UTC, patmmccann approved these changes

2021-12-16 16:21 UTC, merged