fixing the AMP creative integration example
prebid/Prebid.js pull request #7911
Opened 2022-01-05 20:35 UTC by bretg

## Type of change
Documentation

## Description of change
I can't see how the original version of this ever could have worked. AMP requires calling out to Prebid Cache. The original example was calling for Prebid.js, which isn't present in an AMP environment. 

I just copied the instructions at https://docs.prebid.org/adops/setting-up-prebid-for-amp-in-dfp.html

2022-01-06 22:15 UTC, patmmccann approved these changes

2022-01-06 22:17 UTC, patmmccann approved these changes
one minor change

2022-01-06 22:17 UTC, patmmccann commented on integrationExamples/gpt/amp/creative.html
> +  ucTagData.targetingMap = %%PATTERN:TARGETINGMAP%%;
this needs quotes

2022-01-06 22:21 UTC, patmmccann requested changes
Please add the quotes around targeting map

2022-01-07 21:26 UTC, bretg commented on integrationExamples/gpt/amp/creative.html
> +  ucTagData.targetingMap = %%PATTERN:TARGETINGMAP%%;
added

2022-01-10 17:16 UTC, patmmccann approved these changes

2022-01-10 19:35 UTC, merged