Rename Audigent Halo -> Hadron
prebid/Prebid.js pull request #7938
Opened 2022-01-14 01:10 UTC by anthonylauzon

## Type of change
- [X] Refactoring (no functional changes, no api changes)

## Description of change
This change fixes the naming of Audigent's Halo submodules to fit the new Hadron branding.

## Contact
prebid@audigent.com

## Docs Update Link
https://github.com/prebid/prebid.github.io/pull/3509

## Other information
https://github.com/prebid/Prebid.js/pull/7060
https://github.com/prebid/Prebid.js/pull/5777
https://github.com/prebid/Prebid.js/pull/6742

2022-01-14 03:42 UTC, anthonylauzon commented
@ChrisHuie simple rebrand that requires a minor update for a couple of other adapters

2022-01-14 15:26 UTC, anthonylauzon commented
@bretg code side review needed here - thanks

2022-01-21 13:56 UTC, Fawke requested changes
Hi @anthonylauzon,

Do we need a docs update here?

Also, can you please revert the changes made to the package-lock.json file?

2022-01-21 14:21 UTC, anthonylauzon commented
Docs are approved here: https://github.com/prebid/prebid.github.io/pull/3509

package lock reverted

2022-01-21 18:47 UTC, patmmccann commented
This appears to be a breaking change

2022-01-21 18:53 UTC, bretg commented
Patrick is right - this would force every publisher currently using halo to change their in-page config. That's not ideal.

We don't currently support aliases for modules, but perhaps the new hadron module could deal with old "halo" config until 7.0?

2022-01-21 20:10 UTC, anthonylauzon commented
I'm just as happy to duplicate the module until 7.0 so that there is a clear, seamless migration path.

2022-01-21 20:13 UTC, anthonylauzon commented
That said, the change is not breaking - it is the same as deprecating any other module.  Publishers who are currently building the halo modules will need to rename the module configs in their build configurations accordingly.

2022-01-21 22:18 UTC, anthonylauzon commented
I've temporarily re-added the Halo modules for continuity before 7.0, at which point they can be removed.

2022-01-24 22:54 UTC, anthonylauzon commented
@patmmccann @Fawke @bretg this is ready for merge

2022-01-25 10:18 UTC, Fawke approved these changes
Looks good.
@patmmccann Do you mind having a second look? Thanks.

2022-01-25 10:39 UTC, Fawke commented
> I've temporarily re-added the Halo modules for continuity before 7.0, at which point they can be removed.

@anthonylauzon I just realised that you didn't add the test files back for halo. Can you please include them as well so as to maintain a healthy test coverage for the overall project?

2022-01-25 20:51 UTC, patmmccann commented
no longer looks breaking to me, but yes we shouldnt drop the test files

2022-01-25 20:52 UTC, patmmccann requested changes
all the ssp adapters you removed halo support from are a blocker here

2022-01-25 20:52 UTC, patmmccann commented on modules/beachfrontBidAdapter.js
> +  { key: 'hadronId', source: 'audigent.com', atype: 1, queryParam: 'hadronid' }
this is breaking, nevermind

2022-01-25 20:53 UTC, patmmccann commented on modules/ixBidAdapter.js
> +  'hadronId',
definitely breaking....

2022-01-25 20:53 UTC, patmmccann commented on modules/openxBidAdapter.js
> +  hadronId: 'audigentid', // Hadron ID from Audigent
breaking

2022-01-25 22:57 UTC, anthonylauzon commented
test file re-added, reverted SSP changes and will handle bid adapter updates via separate PR(s)

2022-01-26 14:42 UTC, patmmccann commented
you appear to still be modifying the index adapter

2022-01-26 19:18 UTC, patmmccann requested changes
it doesnt seem you reverted all breaking adapter changes

2022-01-26 20:47 UTC, anthonylauzon commented
the only reference to hadron in the ix bid adapter appeared to be in a comment.  inconsistent, so changed and reverted that and another reference.  should be good to merge now.

2022-01-26 20:55 UTC, patmmccann commented
I don't see any more breaking changes but please note @Fawke requested you restore file test/spec/modules/haloIdSystem_spec.js

2022-01-26 21:58 UTC, patmmccann approved these changes
LGTM

2022-01-26 21:58 UTC, anthonylauzon commented
re-added

2022-01-26 21:58 UTC, merged