add B.I. Garage Richmedia Adapter
prebid/Prebid.js pull request #8033
Opened 2022-02-09 12:32 UTC by mediaconsortium-develop

## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```javascript
{
  'bidder': 'bigRichmedia',
  'params': {
    'placementId': '10433394'
  },
  'mediaTypes': {
    'banner': {
      'sizes': [[300, 250], [300, 600], [1800, 1000]]
    }
  },
  'adUnitCode': 'adunit-code',
  'sizes': [[300, 250], [300, 600], [1800, 1000]],
  'bidId': '30b31c1838de1e',
  'bidderRequestId': '22edbae2733bf6',
  'auctionId': '1d1a030790a475',
  'transactionId': '04f2659e-c005-4eb1-a57c-fa93145e3843'
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/pull/3558

## Other information

2022-02-09 15:37 UTC, JulieLorin commented
The CI fails because of other adapters : 
![image](https://user-images.githubusercontent.com/635021/153234738-62f66fbf-4b6c-407d-9be5-9d773313329a.png)

This PR doesn't edit any files (only file addition). Anybody would know why this would fail ?

2022-02-09 15:41 UTC, bretg requested changes

2022-02-10 09:32 UTC, JulieLorin commented on modules/bigRichmediaBidAdapter.js
> +  gvlid: baseAdapter.GVLID, // use base adapter gvlid
The adapter is fully based on Xandr and will make requests using Xandr endpoint. 
Therefore, is it OK to use it ?

2022-02-11 10:28 UTC, JulieLorin commented on modules/bigRichmediaBidAdapter.js
> +  gvlid: baseAdapter.GVLID, // use base adapter gvlid
Thank you. Is there a way to follow this issue ?

2022-02-11 12:50 UTC, bretg commented on modules/bigRichmediaBidAdapter.js
> +  gvlid: baseAdapter.GVLID, // use base adapter gvlid
I'll step aside here. Xandr is willing to represent you with their GVL ID.

2022-02-11 12:51 UTC, bretg commented on modules/bigRichmediaBidAdapter.js
> +const BIDDER_CODE = 'big-richmedia';
this is still an open issue - what's your adapter code: big-richmedia or bigRichMedia?

2022-02-11 13:12 UTC, JulieLorin commented on modules/bigRichmediaBidAdapter.js
> +const BIDDER_CODE = 'big-richmedia';
The adapter code is `big-richmedia`.
The file name has been updated in https://github.com/prebid/prebid.github.io/pull/3558

2022-02-14 17:21 UTC, bretg commented on modules/bigRichmediaBidAdapter.js
> +const BIDDER_CODE = 'big-richmedia';
thanks. Now the actual code reviewer can do his thing. :-)

2022-02-14 17:24 UTC, bretg approved these changes

2022-02-15 19:18 UTC, ChrisHuie approved these changes

2022-02-15 19:22 UTC, merged