Open8 Bid Adapter: Add `advertiserDomains` support to comply with Prebid.js 5.0
prebid/Prebid.js pull request #8127
Opened 2022-03-01 02:19 UTC by hisui

## Type of change

- [x] Other

## Description of change

- test parameters for validating bids

```json
{
    bidder: 'open8',
    params: {
        slotKey: '2ae5a533'
    }
}
```

- contact email of the adapter’s maintainer: tdd-adtech@open8.com
- [x] official adapter submission

2022-03-09 13:41 UTC, patmmccann commented on modules/open8BidAdapter.js
> +import * as utils from '../src/utils.js';
Please only import what you need

2022-03-09 13:42 UTC, patmmccann commented on modules/open8BidAdapter.js
> +const URL = '//as.vt.open8.com/v1/control/prebid';
We no longer support protocol relative, use secure

2022-03-09 13:44 UTC, patmmccann requested changes
Couple change requests

2022-03-10 06:52 UTC, hisui commented
@patmmccann Thank you for the review. I've fixed them as you indicated.

2022-03-11 14:06 UTC, ChrisHuie approved these changes

2022-03-21 19:45 UTC, merged