NativoBidAdapter - Bid data mapping refactor and added QS params on request
prebid/Prebid.js pull request #8196
Opened 2022-03-17 13:43 UTC by jsfledd

## Type of change

- [x] Refactoring (no functional changes, no api changes)

## Description of change
- Refactored the way we keep track of bids internally and map them to our system
- Added new query string parameters to the bid request

2022-03-21 17:20 UTC, ChrisHuie commented
@jsfledd working on sorting out why tests are failing on the install step 🧐

2022-03-30 11:28 UTC, mmoschovas requested changes
@jsfledd can you drop the package.lock change here

2022-03-30 14:32 UTC, jsfledd commented
@mmoschovas I have removed the package.lock from the PR

2022-03-30 14:59 UTC, mmoschovas commented on modules/nativoBidAdapter.js
> +  if (filterData && Array.isArray(filterData) && filterData.length > 0) {
0 is falsey so you can simply say 

`if (filterData && Array.isArray(filterData) && filterData.length) {`

2022-03-30 15:00 UTC, mmoschovas commented
@jsfledd  Thank you for updating. One more super small change and this is good to go

2022-03-30 16:00 UTC, mmoschovas approved these changes

2022-03-30 16:00 UTC, merged