UserID module: better initialization logic
prebid/Prebid.js pull request #8201
Opened 2022-03-21 22:02 UTC by dgirardi

## Type of change

- [x] Bugfix
- [x] Does this change affect user-facing APIs or examples documented on http://prebid.org?

## Description of change

﻿This updates the userID module to avoid premature initialization (https://github.com/prebid/Prebid.js/issues/5447):

 - `pbjs.getUserIds` and `pbjs.getUserIdsAsEids` no longer force initialization of the ID system
 - ID submodules are now initialized after after GDPR consent has been resolved *and* `userSync` configuration has been set
 - both `pbjs.getUserIds` and `pbjs.getUserIdsAsEids` now accept a callback that, if provided, is scheduled run after all ID submodules have filled in their data. Depending on `userSync` configuration, this may neeed to wait for an AUCTION_END event
 - `pbjs.refreshUserIds` now forces an immediate refresh regardless of `userSync` config and returns a promise that completes when all ID submodules have filled in their data. `pbjs.refreshUserIds({refresh: false})` will just return the promise without refreshing.

Note that until https://github.com/prebid/Prebid.js/pull/8185 gets merged, GDPR data cannot be resolved without an auction, so this will prevent any ID from being resolved if the consentManagement module is installed and no auction is started. No additional action should be required to fix this besides the merge.

## Other information

Fixes https://github.com/prebid/Prebid.js/issues/5447
Documentation PR: TBD

2022-03-23 17:52 UTC, patmmccann commented
@dgirardi please note the merge conflict

2022-03-30 10:21 UTC, EskelCz commented
Thanks for this, looks promising.
One suggestion for readability though, `pbjs.refreshUserIds({refresh: false})` is just what we want, but it's not immediately clear what it does. Can it separated into a new method, something like `pbjs.getUserIdsAsync()`?

2022-03-30 15:13 UTC, dgirardi commented
What about adding `getUserIdsAsync` but removing callbacks from the other methods' signatures? Since all of these are part of the public API I'd like to keep changes to a minimum.

2022-03-31 11:57 UTC, EskelCz commented
Sounds good, that would leave the current implementations that are working as they are... and whoever is having issues would switch to the async version.

2022-03-31 12:30 UTC, smenzer requested changes
Overall this looks good. I'm not an engineer so I can't say that every bit of code is written in the best way, but the logic makes sense and I like that it doesn't break existing implementations.

I would like to see the examples page updated to show how to properly use the `pbjs.getUserIds()` method with the new callback function, as well as any related docs (I know the docs PR is still pending). Once all of that is done, I'm happy to approve. 

We will need another engineer to review and approve since this is core.

2022-04-13 13:14 UTC, smenzer commented on test/spec/modules/userId_spec.js
> +    resetConsentData();
I agree completely. a lot of this was from the first iteration of the user id module, so a lot of copy/paste from newer modules and signatures weren't necessarily updated as we made changes.

I think we need to have a few tests that do test *all* id systems for basic processing, but the majority of these tests could probably just be mock id systems to test core functionality

2022-04-13 13:15 UTC, smenzer approved these changes

2022-04-14 17:50 UTC, SKOCHERI approved these changes

2022-04-14 19:01 UTC, smenzer commented
We've got 2 approvals on this, so I'm going to go ahead and merge it in. Thanks for all the work on this one everyone, especially @dgirard and @EskelCz!

2022-04-14 19:01 UTC, merged

2022-04-14 19:58 UTC, EskelCz commented
@smenzer @dgirardi Awesome, thanks a lot for quick resolution. Looking forward to testing it out.