Adds cpexIdSystem
prebid/Prebid.js pull request #8364
Opened 2022-05-03 17:26 UTC by EskelCz

## Type of change
- [x] Other

## Description of change
New User Sync submodule (User ID), called CPExID or Czech Ad ID (caid).
It's use is intended for selected partners in direct communication with our company (cpex.cz).

Covered with basic tests, documented in markdown file.

2022-05-09 20:14 UTC, smenzer requested changes
Please share the link to your prebid docs PR before I can merge this one.

2022-05-09 20:14 UTC, smenzer commented on modules/userId/userId.md
> +            }
this isn't necessary based on your implementation, since you manually pull from browser storage.

2022-05-10 12:55 UTC, EskelCz commented
@smenzer The failing test is from "finteza analytics adapter", which I didn't touch. Locally all test are passing. What should I do?

The docs PR is here: [https://github.com/prebid/prebid.github.io/pull/3768](https://github.com/prebid/prebid.github.io/pull/3768)

2022-05-10 17:59 UTC, smenzer approved these changes
LGTM

2022-05-10 18:57 UTC, merged