Seedtag Bid Adapter: add compliance to usp/ccpa
prebid/Prebid.js pull request #8602
Opened 2022-06-23 12:41 UTC by ybootin

## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Add usp/ccpa compliance

2022-07-04 20:31 UTC, lksharma commented
@ybootin Can you open a docs PR to indicate support for the US Privacy consentManagementUsp module.

2022-07-04 20:32 UTC, lksharma requested changes
@ybootin Can you open a docs PR to indicate support for the US Privacy consentManagementUsp module.

2022-07-05 06:35 UTC, ybootin commented
@lksharma ok done !

2022-07-12 13:15 UTC, ChrisHuie approved these changes

2022-07-12 13:15 UTC, merged