ShowHeroes Bid Adapter: added a new endpoint
prebid/Prebid.js pull request #8635
Opened 2022-07-01 05:45 UTC by vadim-mazzherin

## Type of change
- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter 
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Added a new endpoint to a new our bidder server

- contact email of the adapter’s maintainer: vadim.mazzherin@showheroes.com
- [x] official adapter submission

2022-07-01 13:55 UTC, ChrisHuie commented
@vadim-mazzherin can you please add unit tests for this pr? Also, doesn't seem to have run through our CircleCI integration tests. This usually happens in CircleCi if you are following a fork of Prebid and not the project itself in CircleCI. You can usually fix this by unfollowing your Prebid fork in CircleCI.

2022-07-25 16:40 UTC, patmmccann requested changes

2022-07-25 16:40 UTC, patmmccann commented on modules/showheroes-bsBidAdapter.js
> +const VIRALIZE_ENDPOINT = 'https://api.viralize.com/prebid-sh/'; // @TODO refine the url later
this seems alarming, can you complete this todo?

2022-07-25 16:43 UTC, patmmccann commented
Please resubmit when the unit tests are ready, the docs pr is complete, and the endpoint is in its final form. We're not able to give a meaningful review until that time.

2022-07-25 16:43 UTC, closed without merging