Obtain display-related attributes and browser client hints
prebid/Prebid.js pull request #8730
Opened 2022-07-22 16:55 UTC by carlosfelix

## Type of change

- [ ] Bugfix
- [X] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Obtain display-related client-side attributes and clients hints from browsers that support it 

- contact email of the adapter’s maintainer: carlos.felix@33across.com
- [X] official adapter submission

2022-07-22 19:54 UTC, carlosfelix commented
I've tried many different ways to reproduce the failing tests scenario that I am seeing in the CI, but no luck so far, all the specs are passing on my environment and other envs where I have tried.

2022-07-25 17:14 UTC, patmmccann commented
We're not allowing adapters to access these api's, please modify core and access from core

https://github.com/prebid/Prebid.js/issues/8381

2022-07-25 17:15 UTC, patmmccann requested changes
User agent client hints should be gathered by core

2022-07-25 17:15 UTC, patmmccann commented on modules/33acrossBidAdapter.js
> +  storage.setDataInLocalStorage(UA_DATA_KEY, JSON.stringify(uaData));
why put this in storage?

2022-07-26 14:01 UTC, patmmccann commented
Update: discussed with 33across team on slack, updates pending

2022-07-26 18:04 UTC, macinjosh32 commented
Hi Pat,
We're only intending to collect client hints within our adapter on a temporary basis (through end of Q3) so we can quickly understand the state of various browsers' UA deprecation. We'll be happy to switch the access over to enrichmentFpdModule thereafter if we decide we need it past Q3. It looks like several other modules, such sspBC's adapter and Just ID's User ID sub-module (via an external script) are already collecting these on a more permanent basis, so we were not anticipating any concerns as long as standards are being fairly applied across modules. Placing the values in storage is to help facilitate unit tests and ensure these were available upon initial request since the Client Hints API is asynchronous. Thanks in advance for your understanding.

2022-07-26 20:52 UTC, patmmccann commented
We noticed that as well, which is why we drew the line in the sand to make sure no more were added https://github.com/prebid/Prebid.js/issues/8381

2022-07-27 23:15 UTC, anthonyjl92 commented
Hi Pat, we removed the storage and client hints from this PR - are you able to review the remaining changes? Thanks!

2022-07-28 12:45 UTC, patmmccann approved these changes

2022-07-28 12:46 UTC, merged