Improve Native ad robustness to null values
prebid/Prebid.js pull request #9010
Opened 2022-09-16 12:57 UTC by guiann

## Type of change

- [*] Bugfix

## Description of change

add robustness to null values in native response format.
when receiving those non mandatory null values:

`		"clickUrl": "https://tracking-preprod.omnitagjs.com/tracking/ar?attempt=0340dad174aa18142da537a474446d96\u0026campaign=e2a82912438eaa7d2f234f778f82c274\u0026event_kind=CLICK\u0026url=https%3A%2F%2Fwww.adyoulike.com%3Fauction_price%3D10",
		"displayUrl": null,
		...
		"privacyIcon": null,
		"privacyLink": null,
		"salePrice": null
	}`

we can see this error in console:
`Cannot read properties of null (reading 'url')`

You can see it on this page : 
[native bug example](https://adyoulike.github.io/Tag/prebid/prebid_native.html?env=preprod)

2022-09-19 09:24 UTC, musikele requested changes
please change the function's body and add a test case :)

2022-09-19 09:24 UTC, musikele commented on src/native.js
> +  if (value === null) value = '';
I agree with @dgirardi that it's easier to reason about if the whole function body is just `return value?.url || value`.

2022-09-20 13:05 UTC, guiann commented on src/native.js
> +  if (value === null) value = '';
will do

2022-09-21 09:48 UTC, musikele approved these changes
LGTM

2022-10-03 14:55 UTC, ChrisHuie approved these changes

2022-10-03 14:55 UTC, merged