Freewheel-Prebid
prebid/Prebid.js pull request #9093
Opened 2022-10-09 08:25 UTC by xwang202

## Type of change
- [ ] Feature

## Description of change
1. Added alias `freewheelssp`
2. Updated local parameter `location` 
3. Added the method to get the `advertiserDomains`
4. Added `iframeEnabled` option in `getUserSyncs` method

## Other information

2022-10-10 08:57 UTC, xwang202 commented
@patmmccann can you please review? Thanks.

2022-10-10 13:57 UTC, patmmccann commented on modules/freewheel-sspBidAdapter.js
> +      var location = (bidderRequest && bidderRequest.refererInfo) ? bidderRequest.refererInfo.referer : getTopMostWindow().location.href;
What's wrong with page? This appears incorrect

2022-10-10 14:00 UTC, patmmccann requested changes
Also please re-title your pr to match format of recently merged prs

2022-10-10 14:00 UTC, patmmccann commented on test/spec/modules/freewheel-sspBidAdapter_spec.js
> +      expect(result[0].meta.advertiserDomains).to.deep.equal('');
This must be an array

2022-10-17 09:06 UTC, xwang202 commented on test/spec/modules/freewheel-sspBidAdapter_spec.js
> +      expect(result[0].meta.advertiserDomains).to.deep.equal('');
Updated.

2022-10-18 10:03 UTC, xwang202 commented
@patmmccann the code has been updated. Can you please double check? Thanks.

2022-10-19 16:13 UTC, merged