Aso Bid Adapter: support schain
prebid/Prebid.js pull request #9108
Opened 2022-10-13 08:44 UTC by adserver-online

## Type of change

- [x] Feature
- [x] Code style update
- [x] Refactoring

## Description of change

1. schain support added
2. previously internal parameter 'serverUrl' was renamed to 'server' and published
3. internal parameter 'serverPath' was removed

## Other information
Docs PR https://github.com/prebid/prebid.github.io/pull/4075

2022-10-14 14:52 UTC, patmmccann requested changes
Thanks for your submission!

2022-10-14 14:52 UTC, patmmccann commented on modules/asoBidAdapter.js
> + * WE KINDLY ASK YOU DO NOT COPY THIS ADAPTER UNDER NEW NAME!
This isn't necessary, please remove

2022-10-14 14:52 UTC, patmmccann commented on modules/asoBidAdapter.js
> -  const serverUrl = bidRequest.params.serverUrl || DEFAULT_SERVER_URL;
Note typo in endpoint above

2022-10-14 14:52 UTC, patmmccann commented on modules/asoBidAdapter.md
> +| `attr`    | optional | Custom targeting params | `{keywords: ["a", "b"]}` | `Object`   |
Please note that if you take keywords from bid parameters, you must also take them from ortb2 object

2022-10-18 06:52 UTC, adserver-online commented
@ChrisHuie could you please kick off tests yet again? they stuck with the same error "Could not find a usable config.yml..."

2022-10-19 16:18 UTC, patmmccann approved these changes

2022-10-19 16:18 UTC, merged