Mgid RTD Module : add new RTD module
prebid/Prebid.js pull request #9120
Opened 2022-10-17 10:33 UTC by velichkin

## Type of change
- [x] Feature

## Description of change

Mgid Real-time Data Module

Module Name: Mgid Rtd provider
Module Type: Rtd Provider
Maintainer: [prebid@mgid.com](mailto:prebid@mgid.com)

- [x] official adapter submission

2022-10-21 20:15 UTC, patmmccann commented on integrationExamples/gpt/mgidRtdProvider_example.html
> +<script async src="//www.googletagservices.com/tag/js/gpt.js"></script>
Bad location

2022-10-21 20:15 UTC, patmmccann commented on integrationExamples/gpt/mgidRtdProvider_example.html
> +<script async src="//www.googletagservices.com/tag/js/gpt.js"></script>
Line 4 above is correct

2022-10-23 11:21 UTC, velichkin commented on integrationExamples/gpt/mgidRtdProvider_example.html
> +<script async src="//www.googletagservices.com/tag/js/gpt.js"></script>
Fixed. Removed line 14.

2022-10-27 07:54 UTC, Fawke requested changes
Hi @velichkin,

Your code changes are looking good. Please also add the module in the submodules.json. Take a look at an example [here](https://github.com/prebid/Prebid.js/pull/9135/files#diff-72810593ba1651aea8aecef814185c360f7f2b0c764367bd9c519611b2a63a3c)

And, we would need you to add more documentation and description in the md file. You also need to create a docs PR in this repo - https://github.com/prebid/prebid.github.io

2022-10-27 12:16 UTC, velichkin commented
@Fawke I've added module to .submodules.json and made changes in the md file. Also, here is request to docs repo - https://github.com/prebid/prebid.github.io/pull/4081

2022-10-31 08:12 UTC, Fawke approved these changes

2022-10-31 08:12 UTC, merged