TTD Bid Adapter: add support for regs.gpp
prebid/Prebid.js pull request #9274
Opened 2022-11-22 18:01 UTC by patmmccann

## Type of change

- [X] Other

## Description of change

While we don't yet have a GPP module as described in #8991 ; publishers (or perhaps even CMPs?) may already be setting the gpp string as per https://github.com/InteractiveAdvertisingBureau/openrtb2.x/pull/22 via setConfig eg

` pbjs.setConfig({
   ortb2: {
       regs: {
           gpp: ...,
           gpp_sid: ...
}}})`

This PR supports that scenario, as well as the case where the module puts the string in the same location

2022-11-22 18:54 UTC, patmmccann commented on modules/ttdBidAdapter.js
> +  if (utils.deepAccess(bidderRequest, 'ortb2.regs.gpp') && utils.deepAccess(bidderRequest, 'ortb2.regs.gpp') === 'string')) {
keeping lines 33 and 36 above though?

2022-11-23 17:04 UTC, julian-burger-ttd requested changes
I don't know how expensive all these `deepAccess` calls are...would it be better to store in variable rather than reevaluating each field three times?

2022-11-23 17:54 UTC, patmmccann commented
> I don't know how expensive all these `deepAccess` calls are...would it be better to store in variable rather than reevaluating each field three times?

Makes sense, or we could do the merge deep proposed above if you're okay with whatever supply puts in the regs object

Can you confirm your endpoint will not invalidate requests containing regs.gpp and regs.gpp_sid? Do you need these in an ext field or can we transmit as per 2.6 spec

2022-11-23 18:01 UTC, julian-burger-ttd commented
Generally our bidders are tolerant of "stray" data. Can you point me to the openrtb spec section? I don't see it in 2.6; only found a separate doc about the GPP encoding.

2022-11-23 20:09 UTC, robhazan commented
@julian-burger-ttd - you (and everyone else) should be looking here now for the latest OpenRTB 2.6 spec: https://github.com/InteractiveAdvertisingBureau/openrtb2.x/releases/

You'll find that regs.gpp is indeed reflected there.

2022-11-23 20:32 UTC, julian-burger-ttd commented
Thanks, @robhazan . I think it is fine to merge regs without any interpretation. That is actually preferred since we won't need to update our adapter when our bidder wants to process the enhancements.

2022-11-28 23:06 UTC, patmmccann commented
@julian-burger-ttd I have updated accordingly

2022-11-28 23:07 UTC, patmmccann commented on modules/ttdBidAdapter.js
> +  if (utils.deepAccess(bidderRequest, 'ortb2.regs.gpp') && utils.deepAccess(bidderRequest, 'ortb2.regs.gpp') === 'string')) {
updated

2022-11-29 19:03 UTC, julian-burger-ttd approved these changes

2022-11-29 19:11 UTC, dgirardi approved these changes

2022-11-29 19:18 UTC, merged