Added SmartAdLine Bid Adapter
prebid/Prebid.js pull request #9324
Opened 2022-12-08 11:20 UTC by Robot72

## Type of change

- [x] New bidder adapter  

## Added new bid adapter

- contact email of the adapter’s maintainer
- core logic for the Smartadline Bid Adapter
- test parameters for validating bids:
```
{
  bidder: 'smartadline',
  params: {
    'publisherId': '1234'
  }
}
```

2023-03-15 10:09 UTC, ChrisHuie reviewed
Can you please add support for adomain and schain. Otherwise this looks good

2023-06-07 15:45 UTC, patmmccann commented on modules/smartadlineBidAdapter.js
> +  aliases: [{code: 'smartadline'}],
why is your alias the same as the bidder code

2023-06-07 15:46 UTC, patmmccann commented on modules/smartadlineBidAdapter.js
> +          page: window.location.href
use site.page

2023-06-07 15:46 UTC, patmmccann commented on modules/smartadlineBidAdapter.js
> +        url: '//acdn.adnxs.com/ib/static/usersync/v3/async_usersync.html?' + gdprParams
always use secure

2023-06-07 15:47 UTC, patmmccann commented on modules/smartadlineBidAdapter.js
> +        auctionId: bid.auctionId,
this might be null in prebid 8

2023-06-07 15:47 UTC, patmmccann requested changes
Thanks for the submission!

2023-08-09 13:41 UTC, patmmccann commented
Clearing assignee due to nonresponsive op

2023-11-01 15:22 UTC, patmmccann commented
Stale

2023-11-01 15:22 UTC, closed without merging