Handle voidAuIds in the Adnuntius adapter
prebid/Prebid.js pull request #9356
Opened 2022-12-21 06:41 UTC by antosarho

Adnuntius Bid Adapter: support voidAuIds

## Type of change
- [x] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)

## Description of change
Use the information sent back via voidAuIds from the Adnuntius ad server to stop sending ad requests to inactive ad units within the Adnuntius system.

2023-02-02 21:33 UTC, lksharma requested changes
@antosarho, There are some merge conflicts within this PR. Can you address and resubmit?

2023-02-20 04:19 UTC, lksharma commented
@antosarho, there are merge conflicts with this PR. Please resolve and push your changes.

2023-02-20 04:20 UTC, lksharma requested changes
@antosarho, there are merge conflicts with this PR. Please resolve and push your changes.

2023-03-14 19:15 UTC, lksharma commented on modules/adnuntiusBidAdapter.js
>  //   native.sponsoredBy = ad.text.sponsoredBy?.content || '';
Please remove commented code

2023-03-15 03:52 UTC, antosarho commented on modules/adnuntiusBidAdapter.js
>  //   native.sponsoredBy = ad.text.sponsoredBy?.content || '';
All done.

2023-04-30 09:34 UTC, closed without merging