AIDEM Bid Adapter: added wpar parameters to enviroment
prebid/Prebid.js pull request #9377
Opened 2022-12-27 00:00 UTC by gsollazzo

## Type of change
- [X] Feature

## Description of change
Adding 'wpar' parameters to the enviroment object.

2022-12-27 01:47 UTC, gsollazzo commented
@dgirardi the tests are failing due to a spurious browserstack error. Would you be able to rerun the CI pipeline? Thanks

2023-01-02 12:57 UTC, patmmccann requested changes

2023-01-02 12:57 UTC, patmmccann commented on modules/aidemBidAdapter.js
> +  deepSetValue(payload, 'environment.wpar.innerHeight', window.innerHeight);
Please cover these two lines with a test

2023-01-02 16:07 UTC, darkstarac commented on modules/aidemBidAdapter.js
> +  deepSetValue(payload, 'environment.wpar.innerHeight', window.innerHeight);
Done!

2023-01-03 16:02 UTC, patmmccann approved these changes

2023-01-03 16:02 UTC, merged