admixer adding floor module support and new alias
prebid/Prebid.js pull request #9427
Opened 2023-01-16 12:54 UTC by dariaboyko

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

## Other information

2023-01-19 14:33 UTC, Fawke requested changes
Looks good overall. 
Just make sure that the endpoint uses `https://`  and please provide a docs pr for prebid.org, since you now support floors module, it'll be good to put that in the docs.

2023-01-20 10:16 UTC, dariaboyko commented on modules/admixerBidAdapter.js
> +const ADX_ENDPOINT_URL = 'http://inv-nets.admixer.net/adxprebid.1.2.aspx';
Hi! Thank you for you answer, everything you asked for is done

2023-01-23 08:26 UTC, Fawke commented
Hi @dariaboyko,

Thanks for the making the changes. One more suggestion, since you have added support for floors module, you can open a new docs PR against [this](https://github.com/prebid/prebid.github.io) repo, particularly you'd want to change [this](https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/admixer.md) file.

You can use [this](https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/appnexus.md) as an example.

Rest all looks good.

2023-01-23 08:37 UTC, dariaboyko commented
Hi! Everything is added in [this pull request](https://github.com/prebid/prebid.github.io/pull/4279).

2023-01-23 08:48 UTC, Fawke approved these changes

2023-01-23 08:54 UTC, merged