MinuteMediaPlus Bid Adapter: New Bid Adapter
prebid/Prebid.js pull request #9430
Opened 2023-01-17 14:07 UTC by uditalias

## Type of change
- [x] New bidder adapter   

## Description of change
This is MinuteMediaPlus new bid adapter
Tests are included

- maintainer: hb@minutemedia.com
- test parameters for validating bids:
```
{
  bidder: 'minutemediaplus',
  params: {
    cId: '562524b21b1c1f08117fc7f9',
    pId: '59ac17c192832d0011283fe3',
    bidFloor: 0.0001,
    ext: {
      param1: 'loremipsum',
      param2: 'dolorsitamet'
    }
  }
}
```

2023-02-01 09:08 UTC, uditalias commented
Hey @lksharma @jsnellbaker 
This PR is two weeks old. Please let me know if you have any updates or need something from my side.
Thanks.

2023-02-02 21:12 UTC, lksharma requested changes

2023-02-05 15:51 UTC, uditalias commented on modules/minutemediaplusBidAdapter.js
> +  let { bidFloor, ext } = params;
@lksharma Thanks
The bidder code changed to `mmplus`
The `bidFloor` is fine as it parsed on the server side

2023-02-05 15:54 UTC, uditalias commented on modules/minutemediaplusBidAdapter.js
> +const BIDDER_CODE = 'minutemediaplus';
Bidder code changed to `mmplus`

2023-02-10 02:56 UTC, lksharma approved these changes
LGTM

2023-02-10 02:57 UTC, merged