SmileWanted Bid Adapter : support of eids
prebid/Prebid.js pull request #9440
Opened 2023-01-19 15:53 UTC by MaxSmileWanted

## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Adding of support eids and tests

2023-01-26 15:52 UTC, patmmccann commented on modules/smilewantedBidAdapter.js
> +import { createEidsArray } from './userId/eids.js';
please don't import from other modules, the eids are available on the bid request object

2023-01-27 00:20 UTC, jlquaccia requested changes
Once the logic for getting the eids is updated, think this looks good.

2023-01-31 09:48 UTC, MaxSmileWanted commented
Hello,

We have updated the commit with modifications asked.

2023-01-31 18:56 UTC, jlquaccia approved these changes
LGTM

2023-02-03 18:24 UTC, muuki88 commented
Docs: https://github.com/prebid/prebid.github.io/pull/4289

2023-02-06 13:05 UTC, MaxSmileWanted commented
Can you please merge it to have this modification in the 7.36.0

2023-02-08 14:45 UTC, merged