PremiumAds Bid Adapter: new bid adapter
prebid/Prebid.js pull request #9584
Opened 2023-02-24 04:41 UTC by alexgmax

## Type of change
- [x ] New bidder adapter  
- contact email of the adapter’s maintainer: adops@premiumads.net
- test parameters for validating bids:
```
   {
                        bidder: 'premiumads',
                        params: {
                            adUnitId: 1123568438,
                            floor: 0.3
                        }
   }
```

## Other information
Dev docs pull request: https://github.com/prebid/prebid.github.io/pull/4389

2023-04-07 06:52 UTC, alexgmax commented
Hello @osazos,
Please review for us.

Regards,
Alex

2023-06-07 15:41 UTC, patmmccann commented on modules/premiumadsBidAdapter.js
> +    payload.ext.wrapper.wiid = conf.wiid || bidderRequest.auctionId;
this might be null, you should probably fall back to bidderRequestId

2023-06-07 15:44 UTC, patmmccann requested changes
thanks for your submission!

2023-06-07 15:44 UTC, patmmccann commented on modules/premiumadsBidAdapter.js
> +            url: cookieSync.url + '&adUnitId=' + adUnitId + '&gdpr=' + (gdprConsent && gdprConsent.gdprApplies ? 1 : 0) + '&gdpr_consent=' + encodeURIComponent((gdprConsent ? gdprConsent.consentStrin
rely on the request here, and why not pass gpp?

2023-06-07 15:44 UTC, patmmccann commented on modules/premiumadsBidAdapter.js
> +                'hb_buyid_premiumads': seatbidder.ext.buyid
what does this value represent?

2023-10-09 08:02 UTC, alexgmax commented
Thank you all, please help to to review the changes.

2023-10-21 13:44 UTC, closed without merging