BEDigitch Bid Adapter: New Adapter
prebid/Prebid.js pull request #9603
Opened 2023-02-28 11:45 UTC by beglobal2022

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

## Other information

2023-02-28 14:45 UTC, beglobal2022 commented
@jsnellbaker Document PR: https://github.com/prebid/prebid.github.io/pull/4394

2023-03-14 20:15 UTC, lksharma requested changes

2023-03-26 17:38 UTC, beglobal2022 commented on modules/bedigitechBidAdapter.js
> +      const data = {};
Done

2023-03-27 15:51 UTC, beglobal2022 commented on modules/bedigitechBidAdapter.js
> +      const data = {};
> Query params should be part of the `data` object.

@lksharma This has been fixed.

2023-04-03 15:44 UTC, lksharma approved these changes
LGTM

2023-04-03 15:46 UTC, merged