SmartXSP first version
prebid/Prebid.js pull request #9683
Opened 2023-03-17 14:32 UTC by olivierschaal

## Type of change

- [ ] Bugfix
- [ ] Feature
- [X] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

We propose the first version of our Prebid.js bidder
<!-- For new bidder adapters, please provide the following
- contact email of the adapter’s maintainer
pbjs@smartxsp.io
- test parameters for validating bids:
```
{
  bidder: 'smartxsp',
  params: {
    placementId: 13144370,
    token: '1234'
  }
}
```

2023-03-20 08:17 UTC, olivierschaal commented
Hello does this first version suit requirements?

2023-03-21 14:32 UTC, ChrisHuie commented
@olivierschaal it looks like our integration tests didn't run for this pr. This is usuallly because you are following your fork on CircleCI and not the main Prebid projets. You can see the projects you are following on the left hand side of CircleCII

2023-03-21 14:33 UTC, ChrisHuie commented on modules/smartxspBidAdapter.js
> +          ad: ad.ad
Can you please add support for adomain and schain as well

2023-03-21 14:34 UTC, ChrisHuie commented
Please also submit docs to our docs repo -> https://github.com/prebid/prebid.github.io/pulls

2023-03-23 08:44 UTC, olivierschaal commented
Hello, we create the pull request for the doc and add the management of adomain and schain in the bidder.

2023-04-13 14:25 UTC, ChrisHuie commented
@olivierschaal this lgtm. Can you just pull in master to run our CircleCi implementation tests on this pr 🙏

2023-04-14 14:22 UTC, olivierschaal commented
> @olivierschaal this lgtm. Can you just pull in master to run our CircleCi implementation tests on this pr 🙏

Sorry Chris but I don't understand what I have to do ?

2023-04-20 12:50 UTC, ChrisHuie commented
@olivierschaal can you just pull in recent commits from master into this pr? Just want to double check that it syncs with changes since this was submitted 🙏

2023-05-18 13:06 UTC, ChrisHuie commented
Sorry. Will merge this today 👍

2023-06-06 14:18 UTC, ChrisHuie commented
@olivierschaal tried to merge this but there are some linting issues popping up from testing

 67:9  error  Identifier 'bid_url' is not in camel case  camelcase
  69:7  error  Identifier 'bid_url' is not in camel case  camelcase
  81:5  error  Unexpected console statement               no-console
  85:9  error  'url' is defined but never used            no-unused-vars
  86:9  error  'html' is defined but never used           no-unused-vars
  89:9  error  'accountId' is defined but never used      no-unused-vars
  90:9  error  'language' is defined but never used       no-unused-vars
  91:9  error  'scriptId' is defined but never used       no-unused-vars

2023-06-07 15:36 UTC, patmmccann requested changes

2023-06-07 15:36 UTC, patmmccann commented on modules/smartxspBidAdapter.js
> +          bidParam.region = bid.params.region
not covered in tests, how is this used

2023-06-07 15:36 UTC, patmmccann commented on modules/smartxspBidAdapter.js
> +          bidParam.language = bid.params.language
read from standard locations

2023-06-07 15:36 UTC, patmmccann commented on test/spec/modules/smartxspBidAdapter_spec.js
> +      expect(request.data.auctionId).to.exist.and.to.be.a('string')
this will often be null in prebid 8

2023-07-04 13:31 UTC, olivierschaal commented
Hi @ChrisHuie is everything correct ?

2023-08-09 13:51 UTC, patmmccann requested changes
couple things remain unaddressed

2023-08-09 13:51 UTC, patmmccann commented on test/spec/modules/smartxspBidAdapter_spec.js
> +      expect(request.data.auctionId).to.exist.and.to.be.a('string')
you marked this as resolved but the title of your test suggest you cannot take nulls here. If you are indeed able to, perhaps rename the the test as 'auctionid passed when available'

2023-08-09 13:51 UTC, patmmccann commented on modules/smartxspBidAdapter.js
> +          bidParam.language = bid.params.language
this is not resolved, you should read language from the openrtb location eg how yahoo does here https://github.com/prebid/Prebid.js/blob/509deaa0649824369907e6b76d0a4d045ec84df8/modules/yahoosspBidAdapter.js#L442

2023-11-01 15:19 UTC, patmmccann commented
Closing for lack of engagement

2023-11-01 15:19 UTC, closed without merging