New Adapter: Axis
prebid/Prebid.js pull request #9684
Opened 2023-03-17 17:16 UTC by PyjamaWarrior

doc - https://github.com/prebid/prebid.github.io/pull/4424

2023-03-31 16:52 UTC, Rothalack commented
Hey @PyjamaWarrior I think your code here is good. I'm just concerned with your endpoint. When I test locally I am getting the error Prebid axis ERROR: Server call for axis failed:  0. Continuing without bids. Are you able to test with the integration tests on your end?

I believe this is because my local test is on http, not https, not certain though. I am also seeing 1000+ms response time from your server as well. Is this intended?

2023-04-25 19:01 UTC, Rothalack commented
Hey @PyjamaWarrior , just wanted to check in and see if you had any questions or anything. Are you still working on things on your end?

2023-06-07 15:21 UTC, patmmccann commented on modules/axisBidAdapter.js
> +      tmax: config.getConfig('bidderTimeout')
please prefer the request object to config

2023-06-07 15:21 UTC, patmmccann commented on modules/axisBidAdapter.js
> +      coppa: config.getConfig('coppa') === true ? 1 : 0,
please prefer the request object to config

2023-08-03 15:37 UTC, PyjamaWarrior commented
@Rothalack  Can you check again, please? Now everything seems to be working fine.

2023-08-03 15:56 UTC, Rothalack commented
I'll have a look today. In the meantime, please try to address Pat's feedback above. I should have time to test things in an hour or two.

2023-08-03 19:51 UTC, Rothalack commented
@PyjamaWarrior I got a chance to test, everything looks good and is working. I still think you should address Pat's feedback about using the request instead of config above.

2023-08-09 13:53 UTC, patmmccann commented
Thanks so much @Rothalack ! I'll leave assigned to me to get this last change over the finish line.

2023-08-09 13:55 UTC, patmmccann requested changes
Please change these two locations to look at the request object instead of the configuration.

2023-08-09 13:55 UTC, patmmccann commented on modules/axisBidAdapter.js
> +      coppa: config.getConfig('coppa') === true ? 1 : 0,
@PyjamaWarrior here is an example 

https://github.com/prebid/Prebid.js/blob/509deaa0649824369907e6b76d0a4d045ec84df8/modules/riseBidAdapter.js#L328

2023-08-09 13:55 UTC, patmmccann commented on modules/axisBidAdapter.js
> +      tmax: config.getConfig('bidderTimeout')
@PyjamaWarrior here is an example https://github.com/prebid/Prebid.js/blob/509deaa0649824369907e6b76d0a4d045ec84df8/modules/riseBidAdapter.js#L421

2023-08-09 14:09 UTC, patmmccann requested changes
We don't allow parameters that are just standard request fields

2023-08-24 15:09 UTC, patmmccann requested changes
Two changes are currently required: 

1) iabCat: ['IAB1-1', 'IAB3-1', 'IAB4-3'] is not an allowed parameter, please read this from ortb2.site.cat or pagecat. Publishers don't enjoy setting the same field in specific ways for each adapter. Feel free to include instructions on how publishers can set this parameter or link to https://docs.prebid.org/features/firstPartyData.html

2) You are failing your own test according to the last circleci run

2023-09-12 17:23 UTC, PyjamaWarrior commented
@patmmccann I've fixed tests and iabCat. But i want to ask you about ortb2.site.cat. As you can see, i got this data from bidderRequest as you suggested and its same for all adUnits. Maybe its better to use ortb2Imp from validBidRequests to have categories for every adUnit separately? What do you think about that?

2023-09-14 17:42 UTC, patmmccann commented
IAB hangs it on the site object, but we allow it to change per request. see [ Supplying Auction-Specific Data](https://docs.prebid.org/features/firstPartyData.html#supplying-adunit-specific-data)

2023-09-14 17:43 UTC, patmmccann approved these changes

2023-09-14 17:43 UTC, merged