Vidazoo bid adapter support meta data
prebid/Prebid.js pull request #9749
Opened 2023-04-02 14:49 UTC by saar120

## Type of change
- [X] Refactoring (no functional changes, no API changes)

## Description of change
Add support for passing metaData object from server response.

2023-04-04 17:28 UTC, patmmccann approved these changes

2023-04-04 17:28 UTC, patmmccann requested changes
Please fix your test linting error

2023-04-04 17:48 UTC, patmmccann commented
merging master in should fix actually

2023-04-10 09:27 UTC, saar120 commented
> 

@patmmccann Done.

2023-04-10 14:15 UTC, patmmccann approved these changes

2023-04-10 14:15 UTC, merged