Underdog Media Bid Adapter: Update ttl & referer information
prebid/Prebid.js pull request #9826
Opened 2023-04-18 22:25 UTC by kevpark02

## Type of change

- [x] Feature

## Description of change
* Update ttl to default to 300 seconds
* Update the method of fetching referer information

2023-05-06 11:53 UTC, patmmccann commented on package-lock.json
>        "license": "Apache-2.0",
Please don't change this file in your pr

2023-05-10 19:38 UTC, jlquaccia requested changes
Looks good, but would echo the comment about not modifying the package-lock file.  Also looks like there are some conflicts to resolve as well.

2023-05-17 18:21 UTC, jlquaccia commented
@Jacobkmiller thanks!  Yea, LGTM

2023-05-17 18:21 UTC, jlquaccia approved these changes

2023-05-17 23:15 UTC, merged