MinuteMedia Bid Adapter: Support Coppa param
prebid/Prebid.js pull request #9838
Opened 2023-04-20 14:48 UTC by YakirLavi

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter 
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

**Description of change**
Supporting 'Coppa' param in minuteMedia adapter request.

2023-04-21 17:11 UTC, bretg commented
docs PR https://github.com/prebid/prebid.github.io/pull/4506

2023-04-21 22:30 UTC, patmmccann requested changes

2023-04-21 22:30 UTC, patmmccann commented on modules/minutemediaBidAdapter.js
> +  if (config.getConfig('coppa') === true) {
this could actually change on requestBids, please read off bidrequest.ortb2.regs

2023-05-06 11:26 UTC, patmmccann approved these changes

2023-05-06 11:26 UTC, merged